### ISSUE TITLE
Affichage de plusieurs tuiles pour un même équipement avec plusieurs informations

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#100]
J'ai un équipement Abeille de type Thermomètre avec les infos Température, Humidité, Pression et Batterie, cela me fait 4 tuiles au lieu d'une. Quand je clique sur une des 4 tuiles j'ai bien l'historique des 4 infos...

**Comment by ThibautTrarbach** [comment]
Sera dans la prochaine mise à jour stable.

Cordialement
Thibaut
