### ISSUE TITLE
Pièces vides

### ISSUE THREAD

**Issue by solidkris55** [JeeMateTeam/JeeMate-Project#102]
Bonjour, après avoir lu d'un appétit féroce toute la doc, que j'ai suivi a la lettre une bonne dizaine de fois, j'ai toujours le même problème.
Malgré une communication clairement établi entre mon smartphone et jeemate plugin, mes pièces restent désesperements vides.
J'entends déja le "ALERTE AU GOGOLE...AAAALEEERTE AU GOOOOGOOOOOLE" mdr.

Help please

**Comment by scalz** [comment]
Bonjour,
pour que les équipements apparaissent dans les pièces, il faut que:
- l'équipement soit visible
- types génériques configurés
- et dans le plugin cocher "envoyer" pour les equipements que tu veux importer dans l'app

**Comment by solidkris55** [comment]
Super, j'ai fait tout ça et acheté la version premium parce-que tout ça ça promet. Par contre je ne sais pas si c'est déjà recensé mais les retours d'états ne sont pas mis à jour avant de refresh ou de quitter et revenir sur la tuile concernée.
De plus avec des meross smartgarage, aucune action n'est possible à l'appuie.

**Comment by scalz** [comment]
merci !
par rapport au souci de refresh, es tu en dns jeedom? si c'est le cas, il faut que dans l'app, tu ailles dans le menu config/jeedom, et que tu coches Compatibilité DNS Jeedom. ensuite si ça ne refresh tjs pas. ferme et relance l'app. ça devrait ok.

pour ton garage, comment sont configurés tes types génériques, tu pourrais me mettre une capture d'écran stp ?
l'idéal pour la capture (et aussi pour config les génériques), c'est de passer par le plugin jeemate, on a une page spéciale "raccourci" pour les génériques qui est plus rapide pour la saisie.

![Capture](https://user-images.githubusercontent.com/12609100/111910593-4a207000-8a62-11eb-8fec-3067841dcd8f.PNG)

**Comment by solidkris55** [comment]
Ok alors primo non! Merci a toi de ta réactivité vraiment 
Bon j'ai bien activité DNS, rien de surprenant comme spoilé en tête : alerte au gogole.
Ensuite pour la config en generic, je te joins un screen de la config en full generic sur la porte 1. En effet ça marche mais voilà le fonctionnement tu me diras ce que tu en penses.
![Screenshot_2021-03-21-17-18-54-897_com scalz JeeMate](https://user-images.githubusercontent.com/80977612/111912504-2eb96300-8a6a-11eb-97af-cc4f9dd40fbf.jpg)
C'est plus beau sur la porte 2 certes mais ça ne fonctionne pas...

**Comment by solidkris55** [comment]
Bien entendu le visuel porte 1 n'est que l'état. Les deux autres tuiles sont les action ouverture fermeture

**Comment by scalz** [comment]
en fait tu ne dois pas avoir tes types génériques correctement configurés.
Essaie comme ceci:
- va dans le plugin jeemate, et sur la capture que je t'ai mis plus haut va dans Configration générale
- ensuite onglet Equipement, et sur ton equipement clic sur la roue crantée verte
et configures tes commandes info et actions comme ceci

![Capture](https://user-images.githubusercontent.com/12609100/111914167-2b75a580-8a71-11eb-9602-c3be7918ec3c.PNG)

- ensuite dans l'app, tu réimportes tes equipements configuration/jeedom/regenerer l'interface

**Comment by solidkris55** [comment]
Ouf. Merci tout marche nickel. Juste une remarque qui découle peut être de ma config, mais il est impossible de déclencher en simultané les 2 ouvrants. Il faut attendre que l'état de l'un se refresh pour une l'action sur l'autre s'exécute.

**Comment by scalz** [comment]
cool.
ok je mets ça dans ma todolist. ce sera corrigé prochainement

**Comment by solidkris55** [comment]
Encore merci good job
