### ISSUE TITLE
Scénario indiqué toujours encours malgré qu'il soit fini

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#104]
L'animation indiquant le scénario en cours est toujours active même quand celui-ci est terminé (sur la page des favoris)

**Comment by scalz** [comment]
Salut,

je vais regarder ça. merci pour le feedback

**Comment by scalz** [comment]
salut, est-ce que le problème existe toujours depuis la nouvelle version ?

**Comment by sebfar9172** [comment]
Salut il n'y a plus d'animation donc plus de problème ;)
