### ISSUE TITLE
Géolocalisation

### ISSUE THREAD

**Issue by Cityloue15** [JeeMateTeam/JeeMate-Project#106]
Bonjour, quand je clique sur zones et géolocalisation il ne se passe rien, est-ce une fonctionnalité pas encore active ?

**Comment by Cityloue15** [comment]
Bonjour, il y a seulement moi dans ce cas?

**Comment by ThibautTrarbach** [comment]
Hello,

A tu les fonction prémium sur ton app ?

Cdt
Thibaut

**Comment by Cityloue15** [comment]
J'ai activé "Autorisation de partage des identifiant market (Obligatoire pour la version premium)" dans le plugin, mais dans l'application mobile, je n'ai aucun endroit pour activer les fonctions prenium, ni dasn "A propos", ni dans Confiuration
Cordialement Alexandre

**Comment by ThibautTrarbach** [comment]
C'est dans la configuration de jeedom dans l'app et c'est compte market tout en bas qui doit être marqué en OK. Si il est en NOK il faut avoir les case cocher dans votre jeedom puis cliqué sur compte market.

Cordialement
Thibaut

**Comment by Cityloue15** [comment]
Bonjour j'ai tout coché, comme indiqué
![image](https://user-images.githubusercontent.com/73710807/113837712-688aa900-978e-11eb-9bf1-c59171310bff.png)
Mais quand je clique sur compte jeedom (après avoir redemarré l'app): NOK, il ne se passe rien
![image](https://user-images.githubusercontent.com/73710807/113837889-8ce68580-978e-11eb-987e-ceae870e9451.png)

**Comment by Cityloue15** [comment]
Autant pour moi, il y a deux plugins différents ...

**Comment by ThibautTrarbach** [comment]
Hello,

Yes, il faut acheter le premium et seulement a ce moment cette case peux passer en OK

Ps : Si vous achetée le prémium, vous êtes pas obligé de d'installer le plugin

Cordialement
Thibaut

**Comment by Cityloue15** [comment]
Merci, parfait cela fonctionne, par contre je suis localisé à 29m  de mon domicile (rayon 50m), et le plugin ne me situe pas dans la zone
![image](https://user-images.githubusercontent.com/73710807/113843432-dab1bc80-9793-11eb-981b-ab7361de3ade.png)

![image](https://user-images.githubusercontent.com/73710807/113842671-2fa10300-9793-11eb-8c25-ea9bd389ab1f.png)

**Comment by ThibautTrarbach** [comment]
@Cityloue15 C'est normal il va falloir sortir et entrée de la zone. C'est pas le même system qui gère les 2.

Cordialement
Thibaut
