### ISSUE TITLE
Affichage d'informations dans le résumé non présent dans Jeedom

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#108]
Sur la page d'accueil le résumé affiche beaucoup plus d'information que dans le résumé global dans jeedom

**Comment by sagitaz** [comment]
J'avais fait une demande pour que soit pris en compte "afficher même si nul".

C'est pas ça que tu as ?

**Comment by sebfar9172** [comment]
Je ne suis pas sur de bien comprendre (pour info cela fonctionnait avec la version précédente) : j'ai un résumé global qui m'affiche 8 infos dans jeedom et dans l'application il affiche toutes les infos même celles qui ne sont pas dans  le résumé global.
Ces infos sont affichés juste avec l'icone et comme valeur un "-" ce qui est logique car ce sont des résumés de pièces et donc n'ont pas de valeur au global

<img width="253" alt="Capture d’écran 2021-03-30 093517" src="https://user-images.githubusercontent.com/52531214/112951198-63e54580-913b-11eb-97c3-1397c9cc3133.png">
