### ISSUE TITLE
Perte activation premium

### ISSUE THREAD

**Issue by gihomebe** [JeeMateTeam/JeeMate-Project#110]
Bonjour j avais un disfonctionnement notamment avec les caméras ou l une d elle apparaissait en double. J ai réinstallé l app et depuis je n' ai plus activation même après avoir effacé données Android voire effacer et réinstallé. Message pb if .j ai effacer et recréer équipement flasher nouveau code .pas d activation.

**Comment by ThibautTrarbach** [comment]
Hello,

Tu a cocher les case dans la configuration du plugin ?

Cdt
Thibaut

**Comment by gihomebe** [comment]
Hello j ai tout réinstallé cela fonctionne 
Merci

⁣Télécharger BlueMail pour Android ​

Le 15 avr. 2021 à 22:25, à 22:25, Thibaut Trarbach ***@***.***> a écrit:
