### ISSUE TITLE
Vous n'êtes pas autorisé à effectuer cette action

### ISSUE THREAD

**Issue by Cityloue15** [JeeMateTeam/JeeMate-Project#112]
Bonjour, quand je clique sur un des icones (télé ou lumière), j'ai un message dans jeedom, qu'il m'indique "Vous n'êtes pas autorisé à effectuer cette action" 
Capture ci-dessous:
![image](https://user-images.githubusercontent.com/73710807/115382881-77814a80-a1d5-11eb-821e-28494f752eed.png)
![image](https://user-images.githubusercontent.com/73710807/115382911-80721c00-a1d5-11eb-980c-b9700a57e038.png)

**Comment by ThibautTrarbach** [comment]
Hello,

Rescan ton Qrcode, cela est du a un changement de clée dans ton jeedom.

Cordialement
Thibaut

**Comment by Cityloue15** [comment]
Parfait, merci, y aurait-il une possibilité d'avoir une notification jeedom pour nous indiquer de rescanner le qr code? si le problème arrive chez d'autres utilisateurs ?
