### ISSUE TITLE
Logo ré générer interface ne s'arrête jamais

### ISSUE THREAD

**Issue by Gis70** [JeeMateTeam/JeeMate-Project#113]
Bonjour, 

Le logo avec les barres-graphes qui bougent lors de l'appui sur ré-générer inteface ne s'arrête jamais. Un petit logo "check" vert une fois que c'est fini rassurerait l'user :-)

**Comment by ThibautTrarbach** [comment]
Hello,

C'est déjà ce qu'il se passe. Mais on te l'avoue qu'il a un peux de mal le system. Donc dès fois relancer l'app juste avant de regen l'interface l'aide.

Cordialement
Thibaut

**Comment by Gis70** [comment]
Régler sur la nouvel appli thx
