### ISSUE TITLE
Etat d'ouvrant inversé sous Jeemate

### ISSUE THREAD

**Issue by Gis70** [JeeMateTeam/JeeMate-Project#114]
Etat inversé pour une fenêtre par exemple.

Fermée sous Jeedom
Ouverte sur Jeemate

(jMQTT)
![image](https://user-images.githubusercontent.com/16589132/115772899-f3cf8580-a3af-11eb-8a16-c00f7dc9f242.png)

**Comment by Gis70** [comment]
Toujours présent sur la nouvelle appli.

**Comment by scalz** [comment]
Dans la version de cette semaine, on peut à présent inverser un état il faut passer par le plugin jeemate, page configuration avancée, puis sur un equipement clic roue crantée verte. Il faut passer par le plugin jeemate, car certains ne voulaient pas que l'on modifie leur configuration jeedom core. donc pour satisfaire tout le monde, c'est dans le plugin.

Je clos et rouvrirai à moins que le problème ne subsiste

**Comment by Gis70** [comment]
C'est parfait merci.
