### ISSUE TITLE
[Android] Bonjour, suite à l'installation de la version sur playstore, l'appli reste sur un écran noir. J'avais la dernière version dispo sur votre site de mars et je l'avais désinstallée avant d'installer la nouvelle. Je n'ai pas de message d'erreur ou autre. Elle reste tout simplement bloquée sur un écran noir.

### ISSUE THREAD

**Issue by JeeMateWeb** [JeeMateTeam/JeeMate-Project#133]
0.9.0 Ecran noir ne démarre pas

 ### **_Issue crée via le formulaire du site Jeemate_**

**Comment by Gis70** [comment]
PS : le titre et le contenu du message sont inversés dans le formulaire de votre site.

**Comment by ThibautTrarbach** [comment]
Hello,

Oui c'est une erreur dans le code du site, c'est en cours de debug.

Sinon c'est normal, il y a eux tellement de changement entre les 2. (0.8 et la 0.9)
Et pour information la version store est encore en Beta, on se reserve donc le droit de tout casser jusqu'a qu'une vraie stable soit dispognible.

Cordialement

**Comment by Gis70** [comment]
pas de soucis je veux pas vous spammer ;)

**Comment by ThibautTrarbach** [comment]
Pour info le bug des issue est corrigé sur la version de dev, sera publier se soir

**Comment by Gis70** [comment]
Vous fonctionnez comment pour les betas sur android ? via le canal Beta sur
le play store ?

Le sam. 8 mai 2021 à 21:51, Thibaut Trarbach ***@***.***> a
écrit :

**Comment by ThibautTrarbach** [comment]
Non pour l'instant c'est tout les version sur les store qui sont en beta.

Car pour l'instant on a pas de version stable sur les store. mais plus tard, il y auras un canal BETA

**Comment by scalz** [comment]
je clos. en effet 0.8 et 0.9 n'était plus compatible
