### ISSUE TITLE
Amélioration geofence

### ISSUE THREAD

**Issue by Gis70** [JeeMateTeam/JeeMate-Project#135]
Bonjour,

Version de Jeemate 0.9.0.19+ du playstore
Android 10

Le dernier point de géolocalisation a été fait à environ 100m avant ma maison, ensuite le wifi a été détecté, pour autant, je ne suis pas présent et la dernière géolocalisation envoyée est à 128m.  (distance entre les 2 spots)

![image](https://user-images.githubusercontent.com/16589132/117579807-de1ec780-b0f4-11eb-853c-e6badbc55556.png)

Pourrait - on envoyer une dernière fois la géolocalisation après s'être connecté au wifi, et si le wifi est considéré comme le wifi Home alors devenir de facto présent ?

Merci

**Comment by ThibautTrarbach** [comment]
Hello,

Tu a une nouvelle case dans le plugin qui utilise la position GPS pour améliorer le system.

Cordialement
Thibaut

**Comment by Gis70** [comment]
J'attends de m'en être sorti avec mon ouverture de portail pour clore ou pas. J'ai besoin de valider un peu plus la détection de présence domicile et la dernière distance détectée entre le téléphone et la maison.

**Comment by Gis70** [comment]
Bon il y a des couacs, je pense que mon réseau wifi est détecté et la posi gps n'est pas remise à jour dans Jeemate. De plus j'ai des différences de calculs entre la distance maison Jeemate et la distance que je calcule via le plugin localisation et trajet.

Ca serait possible d'avoir un mode debug verbeux qui montre tout ce qui est fait ? 

Je peux connaitre votre algo avec l'élasticité ? 

J'avais sur android 9 une appli qui s'appelait Jeebud, on pouvait renseigner des distances de détections en fonction de la vitesse véhicule :  
![image](https://user-images.githubusercontent.com/16589132/119537789-b5503080-bd8a-11eb-9dfe-f1f9b8ea0a64.png)

J'arrivais à avoir une détection précise à l'approche de ma maison. Là j'ai des soucis. Je sais pas si je suis le seul ?

Mon algo pour ouvrir mon portail c'est : j'arrive à - de 300m de la maison , et je regarde la tendance sur 30 secondes avec un seuil à 50m. La réponse doit être -1 (je me rapproche de la maison)

Merci pour votre aide.

**Comment by scalz** [comment]
Bonjour,
dsl pour le délai.
L'algo élasticité dans l'app est géré par la dépendance que l'on utilise:
https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/elasticityMultiplier.html
https://pub.dev/documentation/flutter_background_geolocation/latest/flt_background_geolocation/Config/distanceFilter.html

Et Thibaut a récemment  effectué des optimisations dans le plugin afin d'améliorer la précision de la détection. A voir..
