### ISSUE TITLE
Sécurité Face ID 

### ISSUE THREAD

**Issue by diony21** [JeeMateTeam/JeeMate-Project#137]
Bonjour,
Ios 0.9.0
Quand Face ID est activé ainsi que sécurité Plug in Mode, Face ID tourne en boucle lorsque l'on souhaite changer de mode. Il faut forcer l'arrêt de l'appli.
Idem lorsque l'on revient sur l'appli après que celle ci soit restée ouverte en arrière plan.

**Comment by ThibautTrarbach** [comment]
Hello,

C'est un bug connu, nous cherchons encore comment le résoudre.

Cordialement
Thibaut

**Comment by scalz** [comment]
corrigé en version 0.9.1 (24)
