### ISSUE TITLE
[IOS] Ajouter des images 

### ISSUE THREAD

**Issue by JeeMateWeb** [JeeMateTeam/JeeMate-Project#138]
Avoir la possibilité d'ajouter une image par exemple tout en bas je suis dans le groupe Etage pouvoir à ce moment là mettre une image pour pour l'étage, merci d'être a l'écoute je vous souhaite un bon courage et du beau boulot :)

 ### **_Issue crée via le formulaire du site Jeemate_**

**Comment by scalz** [comment]
oki je vais voir ça
