### ISSUE TITLE
[Android] compte jeedom NOK

### ISSUE THREAD

**Issue by JeeMateWeb** [JeeMateTeam/JeeMate-Project#139]
bonjour sur l'app j'ai compte jeedom NOK j'ai bien activé le plugin et j'ai bien scanné le QR code je suis bien sur le réseau wifi mais je n'ai rien qui remonte ds l'app
merci 

 ### **_Issue crée via le formulaire du site Jeemate_**

**Comment by scalz** [comment]
Pour ceci, il faut activer la case partager identifiants market dans le plugin. puis soit relancer l'app, ou alors dans le menu config/jeedom/ cliquer sur Jeedom NOK
