### ISSUE TITLE
iOS_Régénération Impossible depuis MAJ

### ISSUE THREAD

**Issue by diony21** [JeeMateTeam/JeeMate-Project#140]
Bonjour,
J'ai fait la MAJ de l'appli 0.9.1(24) et installé la dernière version beta du plugin. L'appairage et la connexion Jeedom est OK fonctionnent mais la régénération des équipements tourne en boucle... J'ai essayé d'effacer l'interface, désinstaller l'appli, redémarrer le tel et jeedom... mais toujours rien.
Par contre j'ai bien la synthèse dans le bandeau haut.
Que puis je essayer pour régler le soucis?
Merci par avance et félicitations pour votre super boulot.

**Comment by scalz** [comment]
Re.
vu et corrigé ensemble. du coup sera dispo en version (25)
