### ISSUE TITLE
[Android] impossible d'avoir accés au qr code

### ISSUE THREAD

**Issue by JeeMateWeb** [JeeMateTeam/JeeMate-Project#145]
bonjour je ne comprends pas comment acceder au qr code pour appairer.
depuis jeedom dans plugin cela me mets ce plugin est inutile pour votre jeedom donc tres embetant d'avoir acheter une appli qui fonctionne pas du tout.
j'espere avoir de vos news rapidement pour debloquer ceci merci d'avance

 ### **_Issue crée via le formulaire du site Jeemate_**

**Comment by ThibautTrarbach** [comment]
Hello,

Le QrCode est accessibles dans le plugin soit par un button en haut de la page de l'équipement soit sur la page de l'équipement elle même en fonction de si vous utiliser la beta ou pas.

Cordialement
Thibaut

**Comment by scalz** [comment]
Le QrCode est disponible depuis le plugin JeeMate.
Je clos.
