### ISSUE TITLE
Info protocole

### ISSUE THREAD

**Issue by Martien51** [JeeMateTeam/JeeMate-Project#146]
Bonjour
Existe-t-il une documentation sur le protocole pour permettre l'adaptation sur une application perso?
(équivalent ISS Imperihome)

**Comment by ThibautTrarbach** [comment]
Je comprends pas vraiment la demande, l'API est entièrement dédié à l'application et donc vous devriez pas avoir besoin de la documentation. Sachant que l'on se réserve de faire les édit que l'on veux a tout moment.

Cordialement
Thibaut

**Comment by scalz** [comment]
Il n'est pas prévu que l'on développe un protocole documenté pour l'api entre l'app et le plugin. Comme disait Thibaut, l'api est dédié et peut être modifié à tout moment.
Je clos.
