### ISSUE TITLE
[Android] Mise à jour des etats

### ISSUE THREAD

**Issue by JeeMateWeb** [JeeMateTeam/JeeMate-Project#147]
Bonjour, je tiens déjà a vous féliciter pour votre travail, votre application donne accès à un visuel agréable pour l'utilisation de Jeedom. C'est exactement ce qu'il me manquait. 
Je rencontre un petit soucis de retour d'êtat, par exemple lors de l'allumage d'une lampe, il faut tirer contre le bas pour rafraîchir la page et donc, les etats. L'action fonctionne instantanément. Le changement de pièces n'a pas d'effet. J'ai testé sur des ampoules Hue (deconz) et virtuel, le résultat est le même, j'ai bien vérifié les type generique. Que puis-je faire pour diagnostiquer le soucis?
Merci de votre aide.
Damien Thoos
damien@thoos.ch

 ### **_Issue crée via le formulaire du site Jeemate_**

**Comment by damienthoos** [comment]
Petites précisions sur les versions:
Jeedom : 4.1.22 
    - DNS privé avec Reverse Proxy pour gérer le certificat HTTPS, mais j'ai fait les tests avec les DNS Jeedom, même réaction.
JeeMate plugin Premium : beta 2021-06-03 01:07:55
JeeMate App android: 0.9.1+29 (Samsung Galaxy S10, Android 11 DSK 30)

J'ai les mêmes soucis sur l'application iPad.

Je constate un 2ème soucis. Lors que je me déconnecte ou connecte sur un wifi, l'application affiche l'icône attention orange en haut et ne fonctionne plus, en tirant contre le bas pour rafraichir, rien ne change. Il faut quitté l'application et la rouvrir pour que ça fonctionne à nouveau.

Les infos de mon téléphone remontent bien jusqu'au Jeedom. Par contre, je n'ai aucuns téléphones sous l'onglet "Vos Telephones" et je ne peux donc pas faire le backup

**Comment by ThibautTrarbach** [comment]
Hello,

Alors pour le retour d'état, on a actuellement un bug si vous envoyer une pièce a avec auccun équipements dedans.

Ensuite le coup de la connexion réseau le Big et trouver et corrigé dans la version dev. Pour le contourné actuellement je vous conseil de retiré votre wifi dans la case configuration de votre jeedom (application)

Cordialement
Thibaut

**Comment by damienthoos** [comment]
Pour la connexion wifi, j'ai un reverse proxy qui fonctionne aussi dans le LAN avec le DNS public, je n'ai donc pas spécifié le SSID. Mon soucis, c'est que le problème est présent à chaque connexion ou déconnexion de wifi (public, bureau, amis).
Concernant le retour d'état, j'avais bien un objet vide. J'ai bien supprimer l'ensemble des objets vide et configuré au moins un type générique par objet utilisé, mais le soucis reste le même (L'état c'est tout de même mise à jour 2x sur plus de 30 essais).

**Comment by damienthoos** [comment]
Bonjour, j'ai toujours le bug de mise à jour des états. J'ai vu passé des mise à jour, mais le résultat est le même. 
Pour ma part, l'application devient inutile, je ne peux pas mettre à jour manuellement l'état en tirant vers le bas à chaque action et n'être ainsi jamais sur que les états affiché soit actuel. 

J'ai mise les logs en debug, lors d'une commande, on voit bien l'action : jeemate:execCmd, la lampe s'allume, mais l'état sur l'application reste éteint.
Si je tire l'affichage vers le bas (actualisation), l'action: Jeemate::getStates et envoyé et tout est à jours.

Suis-je vraiment le seul qui ai ce soucis? J'ai bien supprimer tout les objets plugin inutilisé. J'ai tenté de réinitialisé dans android et iOS, sans succès.
C'est dommage, je trouve le design de votre votre application belle et les possibilités de personnalisation nombreuses. 

De plus, j'ai toujours le même soucis lors que je connecte ou déconnecte de n'importe quel wifi. Ce qui est spécial, c'est que quand l'application à le symbole orange et que les actions ne fonctionne plus, la géo-loc continue de fonctionner.
Et il y a des réaction bizzard dans la personnalisation, des modifs de couleur ne s'applique pas, si on Kill l'app, a l'ouverture, c'est appliqué. Et impossible de modifié la couleur du Nom de l'objet (le nom en bas de la tuile)

De plus j'avais acheté le pack "Premium". Je me contenterais de l'application officielle ...

Bonne suite et buvez un café ou une bière a ma santé.

**Comment by ThibautTrarbach** [comment]
Hello,

Tu peux me redire ta version de ton app ainsi que de ton plugin ?

Cordialement
Thibaut

**Comment by ThibautTrarbach** [comment]
Ce que je peux juste te dire c'est que actuellement on a 250 personne sur la beta iOS et environs 70 personne en sur l'alpha testflight.

Cordialement
Thibaut

**Comment by damienthoos** [comment]
Merci pour ta réponse.

Jeedom: 4.1.23
Jeedom plugin Jeemate: 2021-06-14 10:16:51
Sur Samsung S10 - JeeMate Android App: 0.9.2+35 (inscrit en testeur beta)
Sur iPad - Jeemate iOSapp: 0.9.1+29

**Comment by scalz** [comment]
Salut,

La personnalisation des couleurs widgets n'est pas terminé, j'ai focus la dernière version pour que vous ayiez un meilleur rendu su tablette.

Concernant le souci de refresh d'état, il faudrait vérifier si le plugin envoie bien le refresh à l'app.
Il faut savoir qu'il y a 2 sortes de refresh dans l'app:
- manuel: on tire l'écran vers le bas. 
- automatique: celui-ci ne passe pas par le même systeme dans le plugin.

Donc pour vérifier ça, il faut:
- activer log debug dans le plugin (j'imagine que c'est fait)
- dans les logs jeedom, supprimer tous (comme ça c'est plus simple pour visualiser)
-  dans l'app cliquer sur une tuile pour envoyer une action à jeedom

là tu devrais avoir 2 choses dans les logs jeedom:
- dans api RPC: le execCmd lors de l'envoi de l'action
- dans le log SSE, la nouvelle valeur de l'état qui est envoyé à l'app. Si rien n'apparait dans ce log, alors c'est que le plugin n'a pas envoyé le refresh à l'app
-

**Comment by damienthoos** [comment]
Depuis aujourd'hui, les sondes supplémentaire de Netatmo ne sont plus affichées. Seul la station de base et l'extérieur fonctionne. Par contre, maintenant, les station favoris remonte lors que l'on ouvre le widget en plein écran. Mais toutes les sondes supplémentaire ne s'affiche plus.
Avant, je retrouvais chaque états indépendant (température, humiditée...) pour chaque sonde. Maintenant, il y a plus qu'une tuile vide pour les sonde supplémentaire, seule la station principale est remplie. De plus. elle s'ouvre sur la station principale lors que l'on clique dessus. 
Avant, on avait l'historique accessible pour chaque valeur, je ne retrouve pas ou afficher les historiques maintenant.

**Comment by scalz** [comment]
j'ai regroupé l'équipement sur une tuile dans la dernière version, la tuile n'est pas terminée, idem dans la page dédiée il y aura les historiques.

**Comment by damienthoos** [comment]
Le kit Netatmo de base comprend une sonde principale alimenté en USB et une sonde extérieur sur pile. Ils possible d'acheter d'autre sonde intérieur sur piles pour les autres pièces de la maison, elles sont le même format que la sonde extérieur avec le CO en plus
![2021-06-15 14_45_59-Netatmopro - Jeedom](https://user-images.githubusercontent.com/84376209/122055094-90c70180-cde8-11eb-8990-9ab11c612e78.png)
![2021-06-15 14_45_27-Netatmopro - Jeedom](https://user-images.githubusercontent.com/84376209/122055100-9290c500-cde8-11eb-87f9-b86b49e8743c.png)

**Comment by damienthoos** [comment]
Par rapport à la taille des tuiles, celle-ci ne gère pas la rotation de l'écran. Le nombre reste identique et celle-ci deviennent énorme. Je ne sais pas si c'est utiliser. Tu vois aussi les sonde supplémentaire qui n'affiche plus rien. 
![Screenshot_20210615-144844](https://user-images.githubusercontent.com/84376209/122055662-25316400-cde9-11eb-8a77-5c46d1bcef38.jpg)
![Screenshot_20210615-144857](https://user-images.githubusercontent.com/84376209/122055668-26fb2780-cde9-11eb-9e12-abc75e948f28.jpg)

**Comment by scalz** [comment]
oki je vais regarder ça. pour info je n'ai pas de netatmo chez moi, donc j'ai fait avec les moyens du bord pour savoir comment le plugin fonctionne :)

Je pense justement ne pas gérer et bloquer le mode paysage sur mobile car je vois pas trop l'intéret, on ne pourra jamais avoir assez d'info en visu, peu utile..

J'attends ton test pour le refresh stp

**Comment by damienthoos** [comment]
Je viens de faire différents tests et rien n'arrive dans jeemateAPISSE. Peut importe si je fais la commande depuis l'interface WEB ou depuis l'application Jeemate.
J'ai seulement 3 Start Session, nouveaux summary, nouveau Event (13h42, 14h48 et 14h52).
Mais rien arrive lors que je fais des actions.

**Comment by damienthoos** [comment]
[jeemate_APISSE.txt](https://github.com/JeeMateTeam/JeeMate-Project/files/6655897/jeemate_APISSE.txt)
[jeemate_ApiRPC.txt](https://github.com/JeeMateTeam/JeeMate-Project/files/6655898/jeemate_ApiRPC.txt)

**Comment by scalz** [comment]
salut,

à tout hasard est-ce que c'est toi qui est passé sur jeedom community concernant tes netatmos additionnels. je t'ai répondu en MP sur community concernant ce sujet :)

**Comment by damienthoos** [comment]
Salut. Non, j'ai seulement fait la demande ici.

Pour info, j'ai testé sur un autre Jeedom, les commande depuis le plugin virtuel fonctionne correctement. Le soucis est donc sur mon install (Qui est plus ancienne et avec plus de plugins)
L'option Carte pour définir des zone ne fonctionne plus depuis la dernière mise à jour.
