### ISSUE TITLE
Équipement Sur sauvegarde IP 0.0.0.0

### ISSUE THREAD

**Issue by Maxcrouz73** [JeeMateTeam/JeeMate-Project#157]
A chaque sauvegarde d'un device il est crée un équipement autorisé dans les users jeedom ca qui crée après un certains nombre de création une erreur :

[MySQL] Error code : 22001 (1406). Data too long for column 'options' at row 1 : UPDATE `user` SET `id` = :id, `login` = :login, `profils` = :profils, `password` = :password, `options` = :options, `rights` = :rights, `enable` = :enable, `hash` = :hash WHERE id = 🆔

**Comment by ThibautTrarbach** [comment]
Corrigé dans les derniere version stable et beta
