### ISSUE TITLE
Cacher les icônes.

### ISSUE THREAD

**Issue by sagitaz** [JeeMateTeam/JeeMate-Project#162]
Dans certaines situations, par exemple utilisation d'une image de fond, l'affichage de l'icône n'est pas utile, dans d'autres situations elle n'est pas voulu.

Avoir une option "afficher l'icône".

**Comment by scalz** [comment]
dispo dans la version à venir.
 Il suffira dans le sélecteur de couleur de choisir la couleur transparente

**Comment by sagitaz** [comment]
Dans la 0.9.9+90

Sélectionné la couleur blanche (transparent) pour l'icône afin de la cacher.

![IMG_20211101_011424.jpg](https://user-images.githubusercontent.com/22213453/139606037-843c6e76-2a47-4d22-89c7-4b1abde5f11f.jpg)
