### ISSUE TITLE
Envoyer tous les résumés pièces (certains sont manquants) lorsque l'app fetch les états

### ISSUE THREAD

**Issue by scalz** [JeeMateTeam/JeeMate-Project#165]
car sinon lors d'une fresh install, des résumés resteront manquants jusqu'à ce que l'app les recoivent.

**Comment by sagitaz** [comment]
Exemple de soucis sur les résumés :

![Uploading u2{b92b977} (aa8a9fba-0a84-4423-9cdc-f0f52a840aba id=0x7f0a037a) …]()

![IMG_20211106_201047.jpg](https://user-images.githubusercontent.com/22213453/140621164-b2660977-8d63-4da0-9d29-8673a337199e.jpg)

Résumé global :

Faire en sorte que les équipements remontés soit bien ceux configuré dans Jeedom. Actuellement tous les équipements correspondant au générique d'un résumé sont remonté.

Résumé pièce :

Idem, ne remonté que les résumés réellement configuré dans Jeedom/Objets
