### ISSUE TITLE
Badge notification ne se desincremente pas

### ISSUE THREAD

**Issue by stonedMoose** [JeeMateTeam/JeeMate-Project#195]
Bonjour,

J'utilise JeeMate sur iOS 15.0.2 et le badge de notification ne fait que s'incrémenter à chaque fois que je reçois une notification.

J'ai beau supprimer les notifications ou vider le menu navigation dans l'application (qui est déjà vide) rien n'y fait...

**Comment by kristobal62** [comment]
Bonjour,
Pour que ça se désincrémente, il faut ouvrir la notif à partir du centre de notif de l'iphone qui t'enverra dans jeemate ensuite.
Solution provisoire ;)

**Comment by ThibautTrarbach** [comment]
Hello,

Je viens de pousser une version beta qui corrige plusieurs problème.
Je la pousse en stable quand on me valide qu'il y a pas de bug bloquant 

Cordialement
Thibaut

**Comment by kristobal62** [comment]
Salut Thibaut,
Dernière beta installée, tout est rentré dans l'ordre.
On va attendre d'autres retours ;)
Merci
