### ISSUE TITLE
Générique action modifier icône

### ISSUE THREAD

**Issue by sagitaz** [JeeMateTeam/JeeMate-Project#196]
Sur les génériques actions, il n'est pour le moment pas possible de modifier l'icône.

![IMG_20211114_092904.jpg](https://user-images.githubusercontent.com/22213453/141673694-01caaf94-397f-4c1f-b9a2-c7abc902bd7c.jpg)

![IMG_20211114_092847.jpg](https://user-images.githubusercontent.com/22213453/141673698-430e3a9d-eefb-4410-a1af-d93b87bee708.jpg)

**Comment by scalz** [comment]
dispo en beta 1.0

**Comment by damienthoos** [comment]
Le changement de l'icône fonction, mais impossible de d'ajouter des commandes, lors du retour en arrière, la commande n'est pas sauvegardé
