### ISSUE TITLE
info batterie sur tablette android

### ISSUE THREAD

**Issue by kristobal62** [JeeMateTeam/JeeMate-Project#198]
Bonjour,
L'info de la batterie ne remonte pas de façon régulière. 
Par exemple depuis ce matin aucune info.
![image](https://user-images.githubusercontent.com/58385012/142629239-ccb8d3b6-73b1-41e9-9940-1fb8a65341fb.png)
A gauche jeemate, à droite fully.  10%d'ecart!
![image](https://user-images.githubusercontent.com/58385012/142630150-2155a6cc-e777-4a7b-8fbd-165330f30813.png)

Jeemate est bien lancé sur la tablette. L'écran s'éteint automatiquement (actuellement géré avec fullykiosk) mais jeemate est toujours lancé, j'y touche pas.
Est ce possible d'avoir un retour de batterie du même genre que fully  c'est à dire tout les 1% si c'est possible (oblectif ne plus se servir de fully ;) )

ma config
![image](https://user-images.githubusercontent.com/58385012/142629504-071f1aaf-8a14-4881-97a9-0f85fcdbb29b.png)

Merci

**Comment by sagitaz** [comment]
@kristobal62 c'et mieux avec les dernière version ?
