### ISSUE TITLE
Amelioration : santé

### ISSUE THREAD

**Issue by kristobal62** [JeeMateTeam/JeeMate-Project#201]
Hello,
Est ce possible d'avoir une pastille sur le "coeur" lors qu'il y a une mise à jour d'un plugin ou autre sans avoir à rentrer dans le widget.

Est possible d'ajouter les changelog ;)

Merci

Et encore beau boulot

**Comment by scalz** [comment]
pour la pastille je vais voir comment je peux faire
pour le changelog, il suffit de swiper droit gauche sur le plugin pour qu'apparaissent le menu changelog/documentation

**Comment by scalz** [comment]
normalement corrigé dans la derniere beta

**Comment by pyreneum** [comment]
Serait il possible d'afficher une popup de bonne prise en charge d'une demande mise à jour d'un/de plugin(s)

**Comment by scalz** [comment]
fonctions disponibles.
