### ISSUE TITLE
Problème d'affichage texte widget multimédia en mode nuit

### ISSUE THREAD

**Issue by i-magin** [JeeMateTeam/JeeMate-Project#205]
Ci-après deux copies d'écran de widgets multimédia (plugin sonos) 
1 - Thème Glass avec mode jour
![Capture décran  2022-03-21 à 23 09 43 (002)](https://user-images.githubusercontent.com/35147476/159372251-2cf790c1-4e0f-40a5-afa6-bd38519c618d.png)

2 - Thème Glass avec mode nuit
![IMG_6871 (002)](https://user-images.githubusercontent.com/35147476/159372352-ece60bc9-7446-4405-8346-6aa4cad101f2.PNG)

En mode nuit, le texte n'est pas visible sur le 1er widget
Plugin 2022-03-21 01:12:10 - Jeemate : Version 1.0.0 build +1037

Merci

**Comment by scalz** [comment]
corrigé dans la prochaine version

**Comment by i-magin** [comment]
Correction ok
