### ISSUE TITLE
[Panel] info bulles multiples

### ISSUE THREAD

**Issue by skillix** [JeeMateTeam/JeeMate-Project#207]
Sur un Panel avec plusieurs USERS, les "bulles" ne s'affichent pas en même temps, seul la dernière sélectionné est affichée

![anoJEEMATEpanel](https://user-images.githubusercontent.com/68369861/162172031-78b9b3c0-8dcd-4246-8c5a-19935324f7b5.gif)

les check box users ne permette pas de activer/désactiver tous les affichages cela ne sert visiblement que pour le calcule de distance. si c'est le résultat attendu, ce n'est pas très clair ;)

**Comment by sagitaz** [comment]
En effet, il faut que je regarde pour avoir les bulles fixe pour chaque users, surtout que j'ai d'autres infos à y ajouter.

Oui je vais revoir la checkbox user, c'est bien l'effet voulu.

**Comment by sagitaz** [comment]
Pour info, j'ai testé d'afficher toutes les popups, cela provoque une erreur, apparement c'est corriger dans une maj de leaflet, je vais voir comment on peut upgrade cela.

**Comment by sagitaz** [comment]
Bon finalement j'ai fait autrement et c'est ok.
Je push un proposition et quand tu cela passe en beta si tu peux tester pour clore l'issue.
![Capture d’écran 2022-06-20 140028](https://user-images.githubusercontent.com/22213453/174597188-f975be1a-7e55-4edb-ab49-0085804e6fd7.png)

**Comment by sagitaz** [comment]
Ok en dernière BETA du 22 juillet.

Sujet à fermer
