### ISSUE TITLE
[App][Mineur] Notification - animation bouton parasite 

### ISSUE THREAD

**Issue by skillix** [JeeMateTeam/JeeMate-Project#211]
dans le menu des notifications, "Autoriser les alerte critique" subit une animation parasite.

https://user-images.githubusercontent.com/68369861/163844480-d0509ddd-fdd2-438c-81f4-4b9b2c5b24a3.mp4

**Comment by scalz** [comment]
il ne s'agit pas d'un bug.
ceci est chargement asynchrone de la valeur de cette case à cocher (le temps mis pour récupérer en natif la permission, variable en fonction des appareils).
je clos. si genant alors on rouvrira, mais dans ce cas il faudra que je mette une animation quoiqu'il en soit pour indiquer qu'il y a un chargement de l'info
