### ISSUE TITLE
Affichage des heures en abcisses

### ISSUE THREAD

**Issue by pyreneum** [JeeMateTeam/JeeMate-Project#213]
Dans les courbes d'une journée seule la date est affichée
L'heure serait plus judicieuse

![Screenshot_20220419-173659__01](https://user-images.githubusercontent.com/68426600/164041932-f0402faa-a4cc-4472-be19-08dbdf0ae5f9.jpg)

**Comment by scalz** [comment]
corrigé en version dev, donc dispo lors de la prochaine release
