### ISSUE TITLE
Ajout tuile geoloc ON/OFF

### ISSUE THREAD

**Issue by pyreneum** [JeeMateTeam/JeeMate-Project#215]
j'aimerai bien avoir une tuile qui active désactive le geoloc 

Actuellement je bascule dans les options car je ne souhaite pas partager l'information tout le temps mais seulement quand on part en vélo ou à pied seul histoire d'avoir une trace gps quasi temps réel

Le reste du temps nous n'utilisons pas vraiment cette option

Madame préfère le partager sa position via maps alors que Jeemate faut mieux a l'exception de ce besoin d'aller dans les menus ;)

Peut être que ça pourrait avoir sa place dans ''création widget''?

**Comment by scalz** [comment]
dispo en prochaine version dans création widget
