### ISSUE TITLE
Bug boucle sur géolocalisation

### ISSUE THREAD

**Issue by sagitaz** [JeeMateTeam/JeeMate-Project#216]
La géolocalisation boucle et renvoie tous les évents.

DNS jeedom ?

Équipements jeemate nouvellement créé ?

Toutes informations utiles pour regrouper aux maximum.

Arrivez vous à reproduire ?

**Comment by skillix** [comment]
DNS Jeedom : oui
Ancien équipement id : 900 le 2nd en 901 non impacté (avec la même tel, même config, même réglage, même backup)

La boucle semble s'arrêter quand on désactivé "élasticité"

Une "demi" boucle s'effectue sur un enregistrement de la config geoloc

**Comment by skillix** [comment]
![image](https://user-images.githubusercontent.com/68369861/164609354-1240be4b-570b-4fcc-849d-65a493994e4e.png)
on dirait que ca suit la boucle de geoloc

**Comment by skillix** [comment]
`Error Code : 6 | Exception Error : Exception: [MySQL] Error code : 40001 (1213). Deadlock found when trying to get lock; try restarting transaction : REPLACE INTO history SET cmd_id=:cmd_id, `datetime`=:datetime, value=:value in /var/www/html/core/class/DB.class.php:102 Stack trace: #0 /var/www/html/core/class/history.class.php(980): DB::Prepare('REPLACE INTO hi...', Array, 0) #1 /var/www/html/core/class/cmd.class.php(2242): history->save(Object(jeemateCmd)) #2 /var/www/html/core/class/cmd.class.php(1691): cmd->addHistoryValue(1, '2022-04-21 06:0...') #3 /var/www/html/plugins/jeemate/core/class/api/APISensor.class.php(87): cmd->event(1) #4 /var/www/html/plugins/jeemate/core/class/api/APIGeoLoc.class.php(453): jeemate\API\APISensor::stateCharging(Object(jeemate\API\APIUtils)) #5 /var/www/html/plugins/jeemate/core/class/api/APIGeoLoc.class.php(85): jeemate\API\APIGeoLoc::updateBattery(Object(jeemate\API\APIUtils), Object(jeemate\API\APIGeoEvent)) #6 /var/www/html/plugins/jeemate/core/api/jeemate.api.php(151): jeemate\API\APIGeoLoc::geoloc(Object(jeemate\API\APIUtils)) #7 {main}`

Je en sais pas si c'est lié mais j'ai cette erreur qui reviens tous les jours, mais comme ca touche l'historique, c'est possible ...

**Comment by skillix** [comment]
après écrasement manuel de l'historique avec l'histo d'un autre équipement, problème résolu, ce qui je pense confirme que le problème se trouve dans l'histo

**Comment by mrstark42** [comment]
Bonjour, 
J'utilise le DNS de chez jeedom, j'ai recréé un nouvel équipement (toujours avec le même téléphone) et plus de boucle, l'ancien équipements et toujours en boucle si je le relance.

**Comment by sagitaz** [comment]
Normalement corrigé dans la version du plugin beta du 25-04-2022

**Comment by skillix** [comment]
ou pas :p
