### ISSUE TITLE
Bouton toggle sur mode n'ayant que 2 enums

### ISSUE THREAD

**Issue by pyreneum** [JeeMateTeam/JeeMate-Project#217]
Il serait intéressant de pouvoir basculer de mode avec un simple clic lorsque le mode ne comporte que deux énumérés

Exemple:
Mode gestion maison : auto | Manu

Sur l'appli ce serait bien si avec un clic on pouvait bascule de mode auto a Manu (et inversement) au lieu d'ouvrir l'interface dédiée aux modes, puis choix du mode opposé puis retour.

L'idée :
1/ chercher nbEnum dans le mode
2/ si seulement 2 enum proposer dans la config de la tuile, "bouton mode toggle" ''true|false''(initialisé a false pour conserver le comportement actuel)

Sur le clic l'action pourrait être seulement ''mode precedent'' dans ce cas on est sûr de basculer de mode

**Comment by pyreneum** [comment]
Ajout provenance kristobal sur discord

Petite question du jour. J’ai ma tuile cinéma (c’est un mode). Quand je clic sur la tuile j’ai qu’un seule mode (c’est volontaire car ça sort du mode automatiquement). Je voulais savoir si c’est possible quand j’appuie sur ma tuile cinéma de ne pas rentrer dedans mais de lancer directement le mode ?

**Comment by scalz** [comment]
disponible dans prochaine version.
en théorie un seul mode=une seule action=type Générique Action

**Comment by pyreneum** [comment]
Perfect!
