### ISSUE TITLE
Filtre applications plugin AndroidTV

### ISSUE THREAD

**Issue by pyreneum** [JeeMateTeam/JeeMate-Project#219]
Suite a la suppression d'application dans la liste de l'equipement AndroidTV, la synchro suivante remonte 2 TVs

Les applications supprimées sont toujours présentes dans la liste sous jeemate

Voir comment filtrer ces applications pour ne disposer que de celles souhaitées sous jeemate (ou sous jeedom puis jeemate)

**Comment by scalz** [comment]
dispo en prochaine version
