### ISSUE TITLE
Utilisation des variables Jeedom pour rendus conditionnel

### ISSUE THREAD

**Issue by pyreneum** [JeeMateTeam/JeeMate-Project#220]
Sujet ouvert aux discussions.

J'avais l'envie d'utiliser "variable(MaVariable)" dans la condition d'un rendu conditionnel
Cas d'utilisation : ajout d'une indication clignotante sur lumiere temporisation en cours pour extinction auto

L'évolution n'est pas immédiate apparement
Peut etre faudrait il que l'utilisateur choisisse quelle(s) variable(s) communiquer à jeemate (à l'instar du choix des équipements) à fin de ne pas remonter l'intégralité des variables si juste 3 sont utiles
Prise en compte du mot clé variable(X) dans les conditions

Non prioritaire mais cette évol pourrait servir a d'autre

**Comment by sagitaz** [comment]
@pyreneum j'ai commencé à faire quelque chose coté plugin, je récupère bien la liste des varibles, choix de celle qu'on envoie à jeemate, par contre je n'ai pas activé car pour le moment je ne trouve pas cela optimum.

Jeedom n'envoie pas d'event lorsque la variable change, donc il faudrait que JeeMate interroge reguliérement pour savoir s'il y a un changement, pas pratique.

**Comment by pyreneum** [comment]
Effectivement pas idéal si tu es pas informé du changement de la variable.. On pourrait avoir une action jeemate qu'on lancerait nous dans les scenar pour communiquer la nouvelle valeur aux devices...un genre de ping ''viens voir les news values''

**Comment by sagitaz** [comment]
Salut,

Ce matin j'ai eu une idée de contournement très simple à mettre en œuvre.

Création d'un virtuel avec des commandes infos variable(maVariable)
![Capture d’écran 2022-09-22 093201](https://user-images.githubusercontent.com/22213453/191685689-85b611d4-8371-4f13-b385-6393fb1df54b.png)

Import de celles-ci dans l'application avec comme type générique "générique".

Il te reste plus qu'à utiliser cette info dans tes rendu conditionnel.

**Comment by scalz** [comment]
Jeedom n'ayant pas été conçu avec un vrai bus central de communication/events, l'utilisation d'un contournement pour cette fonctionnalité risque malheureusement d'impacter les performances sur de plus petits jeedom si cela est mal utilisé..

cf https://github.com/jeedom/core/pull/2021#issuecomment-1357854774

Je clos pour l'instant.
