### ISSUE TITLE
Initialisation de la carte Leaflet dans Géo repérage

### ISSUE THREAD

**Issue by Gis70** [JeeMateTeam/JeeMate-Project#221]
Bonjour,

La carte dans géorepérage se trouve en plein milieu de l'océan.

![image](https://user-images.githubusercontent.com/16589132/166747799-e1eb52ac-e233-4847-8ade-07a37babdd31.png)

On peut l'initialiser à minima en France ? et sur les valeurs de la zone s'il y en a une ?

Merci

**Comment by sagitaz** [comment]
Si ton jeedom est configuré niveau localisation c'est celle ci qui sera prise pour la position de la carte.

Sinon faut faire du padel.  😉

On va regarder pour mettre une position en France par défaut.

**Comment by sagitaz** [comment]
Corrigé en version dev, rien de méchant, une inversion de lat/long sur la position par défaut qui est Paris normalement.
