### ISSUE TITLE
Pas d'affichage des courbes "30m" et "H"

### ISSUE THREAD

**Issue by ThibautTrarbach** [JeeMateTeam/JeeMate-Project#31]
Version testée : 910
en cliquant sur une Tile de température -> ouverture des courbes d'historiques.
les courbes sont ok sauf pour les "30m" et "H".
Côté Jeedom elles sont disponibles

**Comment by EricGE01** [comment]
Fonctionnel en release 1000 pour moi

**Comment by stephaneSBO** [comment]
Ok pour moi aussi en 1000.
Pb pb de visibilité de la courbe, mais la c'est du theming
