### ISSUE TITLE
Plugin favoris météo : tant que l’on ne clique pas dessus une fois, l'icône reste vide

### ISSUE THREAD

**Issue by ThibautTrarbach** [JeeMateTeam/JeeMate-Project#32]
Plugin favoris météo : tant que l’on ne clique pas dessus une fois, l'icône reste vide

**Comment by ThibautTrarbach** [comment]
Même en cliquant sur la météo, en revenant sur home, toujours pas d'icone,
Il y a bien les temps min et max

**Comment by stephaneSBO** [comment]
En 1000, l'icone s'affiche pour moi directement
