### ISSUE TITLE
Résumé sur pièce qui ne s'actualise pas

### ISSUE THREAD

**Issue by ThibautTrarbach** [JeeMateTeam/JeeMate-Project#33]
Sur la page home les résumés sont bien mis à jour, par contre sur les pièces ce n'est pas le cas.

Testé avec résumé fenêtre.

**Comment by stephaneSBO** [comment]
KO en 1000. lampe de n'actualise pas dans une pièce. Ok dans home

**Comment by EricGE01** [comment]
@scalz tu t'es emballé à clore ^^
@stephaneSBO indique que KO pour lui et idem pour moi sur VR

**Comment by scalz** [comment]
oops

**Comment by stephaneSBO** [comment]
idem en 0.8.8+1

Lampe ok sur home; KO sur la pièce
Si lampe éteinte au chargement de l'app, Ok home et OK pièce
ON sur la lampe => ok Home, ok pièce
OFF => ok Home, pièce reste à 1 lampe allumée.
Stéphane
