### ISSUE TITLE
Rendre le mode sélectionné plus visible

### ISSUE THREAD

**Issue by ThibautTrarbach** [JeeMateTeam/JeeMate-Project#34]
Valable dans le plugin Thermostat, Mode et Alarme.

Le mode en cours n'est pas clairement identifiable. L'affichage entre le mode actif et les autres modes n'est pas suffisament contrasté.

L'information est présente sous forme de texte (Actuellement le mode est confort).

Pour une meilleur visibilité ;
Contraster le mode en cours
Contraster le texte affiché
Ou les deux :)

![image](https://user-images.githubusercontent.com/30575266/107922383-3a4bd280-6f70-11eb-9356-3ab9017137f6.png)

**Comment by stephaneSBO** [comment]
Ok en Morphic, mais pas en Glass.

**Comment by stephaneSBO** [comment]
En 1000, ok ces ok comme en 999
