### ISSUE TITLE
A la fermeture de l'app : message d'erreur "JeeMate s'arrête systèmatiquement"

### ISSUE THREAD

**Issue by ThibautTrarbach** [JeeMateTeam/JeeMate-Project#40]
Version 910 mais vu sur versions précedente.

En étant connecté en Wifi ou Datas, on lance Jeemate, après ouverture et quelques secondes on ferme l'application via le bouton "ferme l'application". L'application se ferme mais un message "JeeMate s'arrête systèmatiquement" apparait. Ce message n'est pas un message de l'app
Si on ouvre l'app mais que l'on attend plus longtemps avant de la fermer pas de message d'erreur.
Géolocalisation activée mais non configurée.
J'ai transmis le contenu du message via Telegram (voir mon message du 04/02/21 à 21h10)

**Comment by ThibautTrarbach** [comment]
note à moi-même: il s'agit certainement de la lib geoloc+service background

**Comment by scalz** [comment]
corrigé lors du passage à la nouvelle lib geoloc
