### ISSUE TITLE
Edition Pièce : Save lors d'appuie sur bouton retour physique

### ISSUE THREAD

**Issue by ThibautTrarbach** [JeeMateTeam/JeeMate-Project#43]
Un appui sur le bouton retour de l'app sauvegarde bien les changements, mais si c'est le bouton retour du tel, les modifications de sont pas sauvegardées.

A voir si d'autres écrans en "save sur retour"

**Comment by ThibautTrarbach** [comment]
en fait c'est comme ça pour toutes les pages, je l'ai fait comme si c'était un plein écran afin qu'on n'aie justement pas besoin d'ouvrir la barre android pour faire back.
mais j'avais prévu de remettre le fonctionnement de la barre android un peu plus tard, car en fait je m'en sers pour l'instant, comme d'override, c'est à dire quand j'ai une page qui plante pendant le dev, je peux revenir en arrière.

je le remet dès que possible oki
merci pour le feedback

**Comment by Ssshafi** [comment]
Perso c'est pas la barre android que j'utilise, mais le bouton multifonction (empreinte/retour/home/tâches en cours) qui est en dessous de l'écran. Donc même avec l'app en plein écran, il est disponible.
