### ISSUE TITLE
charging state a pas l'air de se mettre a jour, contrairement au state battery

### ISSUE THREAD

**Issue by canabang** [JeeMateTeam/JeeMate-Project#45]

**Comment by scalz** [comment]
possiblement lié au mm souci de lib http (requete qui fail)
mécanisme de retry implémenté
à voir si cela fixe le souci et que le charging state remonte correctement

**Comment by scalz** [comment]
Cela fonctionne-t-il à présent?

**Comment by canabang** [comment]
oui, ca a l'air de fonctionner

**Comment by scalz** [comment]
super merci.
je clos
