### ISSUE TITLE
Lag lors du scroll

### ISSUE THREAD

**Issue by Zeronozero** [JeeMateTeam/JeeMate-Project#47]
Lag quand on scroll dans les équipements mais pas seulement, ça donne l'impression d'un refresh à 30hz sur toute l'App. Testé sur un Galaxy S21 Ultra à 120hz

**Comment by scalz** [comment]
sur toute l'app ??
ou bien uniquement dans la page de sélection lors de l'ajout de favoris

**Comment by Zeronozero** [comment]
Sur toute l'app, même en allant dans le menu hamburger, on voit un lag quand sa s'ouvre. Ca se voit surtout quand on scroll dans une page longue. Actuellement j'ai juste 4 tuiles donc ça vient clairement pas de là.

**Comment by scalz** [comment]
ok je vais me renseigner s'il y a un truc spécial en rapport avec les surcouches Samsung car jamais eu ce souci ni mes BT. ils me l'auraient remonté ça c'est sûr.
je te tiens au courant, merci pour tes précisions

**Comment by Zeronozero** [comment]
Très étrange, c'est la seule App qui me fait ca, en 120hz tout est ultra fluide partout, aucun lag. J'ai testé en passant en 60hz et/ou en passant en résolution FHD+ au lieu du WQHD+ mais pas de changement, ca lague toujours, on dirais du 30hz de rafraichissement ;-)

**Comment by Zeronozero** [comment]
Petit test avec Nova Launcher juste pour voir avec un autre launcher que One UI 3.1. Ca ne change rien, ca lag pareil. Ca doit bien venir de l'App parce-que j'ai affiché le taux de refresh via les options de développeur et je confirme que l'écran est bien en 120hz quand Jeemate est lancé en plein écran.

**Comment by scalz** [comment]
Moi aussi je trouve cela très étrange, et le coup du lag dans le menu burger encore plus étonnant..

- dans mon analyseur de performances sous androidstudio au niveau du framerate, je ne vois rien de spécial,
- pour l'instant tu es le seul dans ce cas.. aucun de mes BT n'ont ce souci
- j'ai test avec des téléphones moins performants que le tien, y compris avec un samsung S7. et rien de spécial
aucune idée pour l'instant

**Comment by Zeronozero** [comment]
Ok, j'ai fait quelques tests et je crois que ça vient du thème Glass et des transparences. J'ai presque pas d'effet de saccade avec le thème Morphic. Ca se voit quand je slide pour ouvrir le menu principal à gauche. Pas de saccade pour le Morphic mais ça me fait cet effet 30hz avec le Glass. 

J'ai encore un peu de lag même en Morphic mais genre une fraction de seconde quand je scroll vers le bas dans les briques puis ça devient fluide. Pareil pour les équipements ça lag tout le temps en Glass mais c'est mieux en Morphic, ultra fluide et de temps en temps y'a un petit lag.

**Comment by scalz** [comment]
Si seulement j'arrivais à reproduire. Je vais voir ce que je peux faire. Et je vais update mon sdk asap, ils ont peut être corrigé des choses là-dessus concernant certains mobiles. Ma dernière update date d'il y a un mois à peine, et ça va vite les updates.
