### ISSUE TITLE
Debug KNX

### ISSUE THREAD

**Issue by ThibautTrarbach** [JeeMateTeam/JeeMate-Project#50]

**Comment by EricGE01** [comment]
@ThibautTrarbach si tu as besoin de billes complémentaires (log ou autre sur KNX) n'hésites pas

**Comment by EricGE01** [comment]
@ThibautTrarbach je vois que tu as debug le KNX. avec la dernière MAJ du plugin le KNX dans l'app est possible ? quelques soit les éléments ? j'avoue ne pas trop savoir ce que tu as changé du coup je ne sais pas quoi tester ^^

**Comment by ThibautTrarbach** [comment]
J'ai débug une nouvelle fois a l'action, il faut voir si tu a plus des équipements en double

**Comment by ThibautTrarbach** [comment]
Plugin Ok et validée
