### ISSUE TITLE
Ajout commande manquante distanceCenterMeters dans GEOLOC coté plugin

### ISSUE THREAD

**Issue by TaGGoU91** [JeeMateTeam/JeeMate-Project#51]
Hello,

Pour rappel, il manque la commande suivantes côté plugin concernant la géolocalisation cf l'info : 
distanceCenterMeters

Sauf si Scalz l'a retiré

**Comment by ThibautTrarbach** [comment]
Dispo en BETA

**Comment by ThibautTrarbach** [comment]
Binaire Debug Normalement

**Comment by ThibautTrarbach** [comment]
Dispo en stable
