### ISSUE TITLE
Connexion via wifi sur réseau local impossible

### ISSUE THREAD

**Issue by Desaydrone** [JeeMateTeam/JeeMate-Project#59]
Quand je connecte l'app via 4g/5g elle fonctionne correctement et arrive à se connecter à jeedom.

Par contre si je me met en wifi impossible pour l'app de trouver jeedom.

Ce que j'ai testé / vérifié : 

- les informations récupérées par l'app, elles sont bonnes
- quitter l'app et la relancer
-  relancer le téléphone
- supprimer l'équipement jeemate de jeedom et recrée une connexion en étant en wifi

Mais rien n'y fait. Je suis disponible pour d'autres tests

Bon courage pour la suite

**Comment by scalz** [comment]
Salut.

pourrais-tu stp:

- fermer l'app
- mettre le plugin en debug
- effacer les logs du plugin (rpc et node)
- lancer l'app en wifi (4g désactivée pour être sûr)
- et me montrer tes logs rpc et node

**Comment by Desaydrone** [comment]
Et voila, alors niveau log de node j'ai ceci

`{"type":"event","id":"4117","value":"17.8","JeeMateEquip":["1012","1013"]}
{"type":"event","id":"4109","value":"21.9","JeeMateEquip":["1012","1013"]}
{"type":"event","id":"4117","value":"17.7","JeeMateEquip":["1012","1013"]}
{"type":"event","id":"4109","value":"21.8","JeeMateEquip":["1012","1013"]}
{"type":"event","id":"4091","value":"18.6","JeeMateEquip":["1012","1013"]}
{"type":"event","id":"4117","value":"17.8","JeeMateEquip":["1012","1013"]}`

Pour les log RPC je n'ai absolument rien qui s'affiche.

Désolé je n'ai rien d'autre à te proposer pour débuger

**Comment by Desaydrone** [comment]
Est-ce que pas hasard il y à un système de debug côté smartphone pour voir si le soucis ne viens pas de ce côté ?

**Comment by sagitaz** [comment]
J'ai tester depuis le boulot sur un smartphone que j'utilise que pour la musique donc pas de carte sim et connecter sur la box du restaurant.
Apres le scan du qrcode cela tourne en boucle sur "tester la connexion" et cela ne se connecte jamais.

Donc sur un wifi autre que le local.

[jeemate_node.txt](https://github.com/JeeMateTeam/JeeMate-Project/files/6029127/jeemate_node.txt)
[jeemate_ApiRPC.txt](https://github.com/JeeMateTeam/JeeMate-Project/files/6029128/jeemate_ApiRPC.txt)

**Comment by scalz** [comment]
la gestion du wifi ssid est en cours de test. bientot dispo

**Comment by ThibautTrarbach** [comment]
@Desaydrone Par hasard dans les config de l'app, la configuration interne est bonne ? elle pointe bien sur ton jeedom ?

**Comment by Desaydrone** [comment]
@ThibautTrarbach oui l'URL interne est la bonne je n'ai pas vu d'erreur

**Comment by Desaydrone** [comment]
En version 8.9+1 le problème est réglé pour moi !! Merciiiiiiiii

**Comment by Desaydrone** [comment]
Information complémentaire sur le sujet :

En cas d'utilisation d'un smartphone sous android 10, il cherche a se connecté au dns en ipv6, donc si on hébergé sur sont réseau son propre DNS il faut que celui ci puisse répondre en IPV6 et pour ceux qui ont une freebox il faut penser à activé cette fonctionnalité sur votre box et renseigné l'adresse ipv6 de votre dns local

![image](https://user-images.githubusercontent.com/15471688/110213968-b1ef8c00-7ea2-11eb-8603-8cfadbe84e72.png)
