### ISSUE TITLE
Problème d'affichage des thermostats en mode tablette

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#60]
Sur une tablette, il y a un soucis d'affichage de la température et des modes
![Screenshot_20210215-134407](https://user-images.githubusercontent.com/52531214/108030842-2798d280-7030-11eb-89b1-504692349b33.jpg)

**Comment by scalz** [comment]
merci pour le retour. je vais corriger ces soucis de responsive dans la semaine, pour les boutons du moins, et si j'ai le temps pour mon widget thermostat

**Comment by sebfar9172** [comment]
Je clos
