### ISSUE TITLE
Aucun retour d'état ne fonctionne sur les équipements

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#61]
Pour avoir un suivi, j'arrive à ajouter des équipements mais les états (lampe allumé ou pas, alarme activée ou pas, ...etc) ne se modifient pas ...[
[getinstall.txt](https://github.com/JeeMateTeam/JeeMate-Project/files/5986787/getinstall.txt)
[jeemate_node.txt](https://github.com/JeeMateTeam/JeeMate-Project/files/5986790/jeemate_node.txt)

](url)

**Comment by scalz** [comment]
pourrais-tu stp:

- fermer l'app
- mettre le plugin en debug
- effacer les logs du plugin (rpc et node)
- lancer l'app en wifi (4g désactivée pour être sûr)
- changer un état (depuis jeedom ou l'app)
- et me montrer tes logs rpc et node

**Comment by sebfar9172** [comment]
Voici je n'ai rien dans node après l'effacement et les manips
[jeemate_ApiRPC.txt](https://github.com/JeeMateTeam/JeeMate-Project/files/5988012/jeemate_ApiRPC.txt)

**Comment by scalz** [comment]
si tu reboot ton tel, pas mieux ??

**Comment by sebfar9172** [comment]
Salut oui c'est mieux je progresse ... J'ai juste les équipements Alarm : 
- sur la tuile, c'est marqué Off mais je ne sais pas d'où vient cette info alors que mon alarme est activée
- sur le détail, c'est marqué Désactivée alors que l'alarme est active

**Comment by scalz** [comment]
oki. donc tu me confirmes que tu n'as plus de souci concernant le refresh de manière générale pour les tuiles ?
j'ai corrigé la tuile Alarme, j'avais une coquille.
si c'est bon, on peut cloturer cette issue, et gérer l'alarme dans l'autre en cours

**Comment by sebfar9172** [comment]
Tout à fait on clos celle là
