### ISSUE TITLE
Pas de Graph à partir des résumés ou des groupes

### ISSUE THREAD

**Issue by Ssshafi** [JeeMateTeam/JeeMate-Project#63]
Lorsque l'on clique sur un résumé (températures par ex.) on obtient les tiles de toutes les sondes de temp., mais lors d'un clique sur celles-ci, un overlay gris apparaît mais pas de graph.
Idem sur les tiles d'un groupe de favoris.

**Comment by scalz** [comment]
je l'ai sans doute déjà corrigé depuis la dernière version car cela fonctionne de mon côté

**Comment by scalz** [comment]
Cela fonctionne-t-il à présent ?

**Comment by scalz** [comment]
je clos cela a déjà été corrigé
