### ISSUE TITLE
Intégration station netatmo

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#64]
Salut
Serait il possible de prévoir l'intégration de la station netatmo (Pluviomètre, ... etc) car je n'utilise pas le plugin weather ?
Merci

**Comment by scalz** [comment]
oui c'est possible, avec plaisir :)
je te recontacterai sur discord pour qu'on voit ça. car j'aurai besoin de certaines infos supplémentaires concernant ce plugin.

**Comment by sebfar9172** [comment]
Je reste disponible pour te donner toutes les infos
