### ISSUE TITLE
Mode en double

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#66]
J'ai un mode Lever/Coucher, il apparait bien dans le menu du mode, dans la liste déroulante il apparait 2 fois (donc autant de fois qu'il y de mode) : 
- le premier choix : j'ai retour mode précédent / Coucher / Lever
- le second choix : c'est vide

**Comment by scalz** [comment]
cela ressemble à un problème de générique.
Tu dois avoir une commande info normalement pour ton equipement Lever/Coucher,
et lui affecter un générique. 
puis regen

**Comment by sebfar9172** [comment]
C'était bien cela :)
