### ISSUE TITLE
Plugin Enedis

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#67]
Salut
Je continue ma liste au père noel :) 
Cela serait possible d'intégrer le plugin Enedis ?
Merci

**Comment by scalz** [comment]
J'ai mis en enhancement. mais quel est le besoin exact au niveau de ce plugin (je n'utilise pas).
car si ce ne sont que des infos, il est sans doute possible de configurer des types génériques existants sur ceux-ci.
d'autant que bientot on pourra aussi changer les icones pour toutes les tuiles.
Par contre j'ai prévu qq chose pour le plugin suivi conso

**Comment by sebfar9172** [comment]
Salut en fait je peux utiliser des génériques mais je voulais savoir si je pouvais avoir une tuile unique avec par exemple la consommation annuel et dans le détail les infos conso journalières, horaires ....
<img width="143" alt="Capture d’écran 2021-02-18 140004" src="https://user-images.githubusercontent.com/52531214/108360529-a426df00-71f1-11eb-8369-8fccb4d14877.png">

**Comment by scalz** [comment]
ok. je note ;)
