### ISSUE TITLE
Plugin: problème encodage états

### ISSUE THREAD

**Issue by scalz** [JeeMateTeam/JeeMate-Project#69]
Lorsqu'un mode (par exemple pour Thermostat ou Mode), contient un "é" dans son libellé, il n'est pas transmis dans les events. Mais coté rpc c'est bon.

Ex: un mode "Présent" renvoie "Prnsent"

**Comment by scalz** [comment]
Il s'agit en fait d'un bug dans le listener de jeedom. Ce n'est pas le plugin JeeMate qui renvoie une valeur erronée, mais Jeedom lui-meme.

L'issue sera résolue, lorsque la team Jeedom aura corrigé

**Comment by ThibautTrarbach** [comment]
Resolu grâce a un patch temporaire. Mais ralentie l'envoi d'event.

**Comment by ThibautTrarbach** [comment]
Normalement Dispo en BETA
