### ISSUE TITLE
pas de connexion en wifi (hors wifi local jeedom)

### ISSUE THREAD

**Issue by jolypas** [JeeMateTeam/JeeMate-Project#70]
Bonjour

ma connexion est OK en 4G, en wifi sur le même réseau que jeedom, mais si je suis en wifi sur un autre réseau (j'ai deux réseaux à la maison séparés pour la domotique et le reste) pas de connexion jeemate - jeedom

merci

**Comment by scalz** [comment]
Bonjour,

C'est déjà dans la todo et c'est en cours de dev.

Duplicate de https://github.com/JeeMateTeam/JeeMate-Project/issues/39

Donc je ferme cette issue.

**Comment by jolypas** [comment]
désolé j'avais vu mais pensais à un autre problème , ma connexion fonctionnant bien en wifi local et en data (manque wifi remote)

**Comment by scalz** [comment]
pas de souci. c'était bien ça. j'ai presque fini de gérer le ssid. si j'ai le temps ce sera dans la release de ce we, sinon semaine prochaine.
