### ISSUE TITLE
Ajouter la possibilité de customiser les notifications

### ISSUE THREAD

**Issue by scalz** [JeeMateTeam/JeeMate-Project#72]
- groupes
- icone+couleur par groupe (déjà supporté par l'App)
- filtres dans l'App (terminé)

**Comment by ThibautTrarbach** [comment]
Disponible depuis la dernière beta du plugin.

Fonctionne grâce a la case titre. Si auccun paramètre mis dans celle ci, alors pas de changement. Par contre en cas de paramètre, le champs entre en action.

Options Dispo : 
- title
- groupName
- iconColor
- customIcon

 Cela doit être écris comme ca : 
_**1er option**_=_**1er Valeur**_;_**2nd option**_=_**2nd Valeur**_  etc etc etc 

Exemple : 
 
![image](https://user-images.githubusercontent.com/30575266/108611836-cfbceb80-73e2-11eb-9fe8-a385291cac57.png)
