### ISSUE TITLE
Le mode indiqué n'est pas le mode sélectionné 

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#75]
<img width="1097" alt="Capture d’écran 2021-02-22 105915" src="https://user-images.githubusercontent.com/52531214/108692590-17379a80-74fd-11eb-8e88-8a4416dd612a.png">
Dans le menu mode j'ai mon mode mais il m'indique que je suis en mode coucher alors que sous jeedom le mode sélectionné est lever

**Comment by scalz** [comment]
Cela doit être car tu as mis le type "Générique" pour l'état.
J'utilise le plugin Mode, et voici comme il configure par défaut les génériques

![Capture](https://user-images.githubusercontent.com/12609100/108694106-e8babf00-74fe-11eb-9310-9c92049309ef.PNG)

**Comment by sebfar9172** [comment]
C'était bien cela par contre je ne sais pas comment générique est arrivé là car je n'ai y ait pas touché, cela première fois que j'y vais car avant je n'en n'ai jamais eu besoin

**Comment by scalz** [comment]
oui c'est bizarre. tant mieux si ça fonctionne.
Je passe en résolu du coup :)
