### ISSUE TITLE
Soucis sur l'état des alarmes

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#76]
Salut
Lors que je vais sur le menu Alarme, toutes mes alarmes sont désactivées alors que sous jeedom la majorité des alarmes sont activées...
Si je vais sur jeedom que je désactive l'alarme sur laquelle je suis dans le menu alarme et que je l'active, elle passe bien à activée. Par contre si je sors du menu alarme et que je reviens dessus elle est affichée désactivée alors que sur jeedom elle est toujours activée

**Comment by scalz** [comment]
ok je vais regarder ça j'ai une idée. faut que je check.
par contre tu me confirmes que sur la page Alarme, c'est uniquement le widget qui a ce souci. Le libellé "Actuellement l'alarme est .." est correct  lui ?

**Comment by sebfar9172** [comment]
non le libellé est faux aussi ...

**Comment by sebfar9172** [comment]
Je corrige finalement je confirme que le libellé est non seul le widget est faux

**Comment by sebfar9172** [comment]
J'avais des alarmes qui étaient mal configurés au niveau des génériques

**Comment by scalz** [comment]
Problème résolu, est-ce que je peux clore cette issue ?

**Comment by sebfar9172** [comment]
En effey
