### ISSUE TITLE
Problème d'icone dans les notifications

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#77]
Bonjour

J'envoi une notification avec le paramètrage ci-dessous et j'ai un "i" qui apparait à la place de l'icone

title=MATIN;customicon=fas fa-sun;groupName=Lever;iconColor=00ff00

**Comment by scalz** [comment]
erreur de typo:
c'est customIcon au lieu de customicon.

Testé et fa-sun fonctionne je clos :)
