### ISSUE TITLE
Notifications multiples

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#80]
![Screenshot_20210222-212409](https://user-images.githubusercontent.com/52531214/108765742-770d6000-7554-11eb-90e4-2e0168caa683.jpg)
Bonsoir
J'ai des notifications triples quand je fais appelle à la commande notification de jeemate 

title=SAUVEGARDE EN COURS;customicon=fas fa-save;groupName=Mise à jour;iconColor=8000ff

**Comment by scalz** [comment]
hmmm. tu reçois 3 notifs dans android ? ou bien c'est  dans l'app?
je viens d'essayer ta commande dans un scénario tout bête avec une seule action pour la notif,  et je reçois bien une seule notif pourtant.

**Comment by scalz** [comment]
autant pour moi dsl. je viens de voir, et je viens de corriger. ce sera dans la prochaine version

**Comment by sebfar9172** [comment]
Top merci

**Comment by scalz** [comment]
sera dans la version d'aujourd'hui.
je ferme. on réouvrira si non fonctionnel mais je ne pense pas :)
