### ISSUE TITLE
Gestion tête thermostatique.

### ISSUE THREAD

**Issue by sagitaz** [JeeMateTeam/JeeMate-Project#81]
Salut,

Comment gérer la configuration des génériques sur des têtes thermostatiques ?
J'ai essayer plusieurs type mais impossible depuis une tuile d'avoir la remonté de consigne et surtout la possibilité de la modifier.

**Comment by scalz** [comment]
Hello,
ça doit être faisable qu'as-tu comme infos et actions pour ton &équipement stp ?

**Comment by sagitaz** [comment]
Je vais essayer de te donner le maximum d'informations.

Pour le Zigbee, c'est un modele Danfoss Ally.
![thermostat-zigbee-cmd](https://user-images.githubusercontent.com/22213453/108819273-eddd4400-75ba-11eb-9b33-30e2d7dace8d.PNG)
voici le Json Deconz :
`{
    "106": {
        "config": {
            "battery": 76,
            "displayflipped": false,
            "heatsetpoint": 1850,
            "locked": false,
            "mountingmode": false,
            "offset": 0,
            "on": true,
            "reachable": true,
            "schedule": [],
            "schedule_on": false
        },
        "ep": 1,
        "etag": "6c7470f017f41c5bdfd9f9fbb7434aaf",
        "lastseen": "2021-02-23T08:39Z",
        "manufacturername": "Danfoss",
        "modelid": "eTRV0100",
        "name": "Thermostat cuisine",
        "state": {
            "errorcode": null,
            "lastupdated": "2021-02-23T08:36:32.489",
            "mountingmodeactive": false,
            "on": true,
            "temperature": 1938,
            "valve": 5,
            "windowopen": null
        },
        "swversion": "01.02.0008 01.02",
        "type": "ZHAThermostat",
        "uniqueid": "84:2e:14:ff:fe:20:54:bd-01-0201"
    },
    "107": {
        "config": {
            "battery": 76,
            "on": true,
            "reachable": true
        },
        "ep": 1,
        "etag": "44f8baff5e086f4b07dfda2361f76d58",
        "lastseen": "2021-02-23T08:39Z",
        "manufacturername": "Danfoss",
        "modelid": "eTRV0100",
        "name": "Thermostat cuisine",
        "state": {
            "lastset": "2021-02-22T01:10:54Z",
            "lastupdated": "2021-02-23T07:11:52.543",
            "localtime": "2021-02-23T08:11:49",
            "utc": "2021-02-23T07:11:49Z"
        },
        "swversion": "01.02.0008 01.02",
        "type": "ZHATime",
        "uniqueid": "84:2e:14:ff:fe:20:54:bd-01-000a"
    }
}`
Pour le Zwave c'est un Devolo home control
![thermostat-zwave-cmd](https://user-images.githubusercontent.com/22213453/108819612-59271600-75bb-11eb-9d0a-ea83f3e5287f.PNG)
`{
"state" : "ok",
"code" : 0,
"result" : {
"associations" : [
],
"instances" : {
"1" : {
"updateTime" : 1614069602,
"commandClasses" : {
"49" : {
"data" : {
"1" : {
"updateTime" : 1614069602,
"help" : "",
"typeZW" : "Decimal",
"genre" : "User",
"read_only" : true,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Temperature",
"val" : 19.81,
"pendingState" : null,
"type" : "float",
"data_items" : "Read only",
"value_id" : 72057594126811150,
"units" : "C",
"write_only" : false
},
"updateTime" : 1614069602
},
"name" : "COMMAND_CLASS_SENSOR_MULTILEVEL"
},
"67" : {
"data" : {
"1" : {
"updateTime" : 1614069602,
"help" : "",
"typeZW" : "Decimal",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Heating 1",
"val" : 18,
"pendingState" : null,
"type" : "float",
"data_items" : "A decimal",
"value_id" : 72057594127106060,
"units" : "C",
"write_only" : false
},
"updateTime" : 1614069602
},
"name" : "COMMAND_CLASS_THERMOSTAT_SETPOINT"
},
"70" : {
"data" : {
"1" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Schedule",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Monday",
"val" : "SwitchPoint",
"pendingState" : null,
"type" : "Schedule",
"data_items" : "Unknown",
"value_id" : 72057594127155220,
"units" : "",
"write_only" : false
},
"2" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Schedule",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Tuesday",
"val" : "SwitchPoint",
"pendingState" : null,
"type" : "Schedule",
"data_items" : "Unknown",
"value_id" : 72057594127155230,
"units" : "",
"write_only" : false
},
"3" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Schedule",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Wednesday",
"val" : "SwitchPoint",
"pendingState" : null,
"type" : "Schedule",
"data_items" : "Unknown",
"value_id" : 72057594127155250,
"units" : "",
"write_only" : false
},
"4" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Schedule",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Thursday",
"val" : "SwitchPoint",
"pendingState" : null,
"type" : "Schedule",
"data_items" : "Unknown",
"value_id" : 72057594127155260,
"units" : "",
"write_only" : false
},
"5" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Schedule",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Friday",
"val" : "SwitchPoint",
"pendingState" : null,
"type" : "Schedule",
"data_items" : "Unknown",
"value_id" : 72057594127155280,
"units" : "",
"write_only" : false
},
"6" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Schedule",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Saturday",
"val" : "SwitchPoint",
"pendingState" : null,
"type" : "Schedule",
"data_items" : "Unknown",
"value_id" : 72057594127155300,
"units" : "",
"write_only" : false
},
"7" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Schedule",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Sunday",
"val" : "SwitchPoint",
"pendingState" : null,
"type" : "Schedule",
"data_items" : "Unknown",
"value_id" : 72057594127155310,
"units" : "",
"write_only" : false
},
"8" : {
"updateTime" : 1614069602,
"help" : "",
"typeZW" : "List",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Override State",
"val" : "None",
"pendingState" : null,
"type" : "List",
"data_items" : "None;Permanent;Temporary",
"value_id" : 72057594127155330,
"units" : "",
"write_only" : false
},
"9" : {
"updateTime" : 1614069602,
"help" : "",
"typeZW" : "Byte",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Override Setback",
"val" : 127,
"pendingState" : null,
"type" : "int",
"data_items" : "A byte between 0 and 255",
"value_id" : 72057594127155340,
"units" : "",
"write_only" : false
},
"updateTime" : 1614069602
},
"name" : "COMMAND_CLASS_CLIMATE_CONTROL_SCHEDULE"
},
"117" : {
"data" : {
"0" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "List",
"genre" : "System",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Protection",
"val" : "Unprotected",
"pendingState" : null,
"type" : "List",
"data_items" : "No Operation Possible;Protection by Sequence;Unprotected",
"value_id" : 72057594136313860,
"units" : "",
"write_only" : false
},
"updateTime" : 1
},
"name" : "COMMAND_CLASS_PROTECTION"
},
"128" : {
"data" : {
"0" : {
"updateTime" : 1614069602,
"help" : "",
"typeZW" : "Byte",
"genre" : "User",
"read_only" : true,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Battery Level",
"val" : 84,
"pendingState" : null,
"type" : "int",
"data_items" : "Read only",
"value_id" : 72057594128105470,
"units" : "%",
"write_only" : false
},
"updateTime" : 1614069602
},
"name" : "COMMAND_CLASS_BATTERY"
},
"129" : {
"data" : {
"0" : {
"updateTime" : 1613224206,
"help" : "",
"typeZW" : "List",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Day",
"val" : "Tuesday",
"pendingState" : null,
"type" : "List",
"data_items" : "Friday;Monday;Saturday;Sunday;Thursday;Tuesday;Wednesday",
"value_id" : 72057594128121860,
"units" : "",
"write_only" : false
},
"1" : {
"updateTime" : 1613224206,
"help" : "",
"typeZW" : "Byte",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Hour",
"val" : 1,
"pendingState" : null,
"type" : "int",
"data_items" : "A byte between 0 and 255",
"value_id" : 72057594128121870,
"units" : "",
"write_only" : false
},
"2" : {
"updateTime" : 1613224206,
"help" : "",
"typeZW" : "Byte",
"genre" : "User",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Minute",
"val" : 53,
"pendingState" : null,
"type" : "int",
"data_items" : "A byte between 0 and 255",
"value_id" : 72057594128121890,
"units" : "",
"write_only" : false
},
"updateTime" : 1613224206
},
"name" : "COMMAND_CLASS_CLOCK"
},
"132" : {
"data" : {
"0" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Int",
"genre" : "System",
"read_only" : false,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Wake-up Interval",
"val" : 300,
"pendingState" : null,
"type" : "int",
"data_items" : "An integer between 2147483648 and 2147483647",
"value_id" : 72057594136559620,
"units" : "Seconds",
"write_only" : false
},
"1" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Int",
"genre" : "System",
"read_only" : true,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Minimum Wake-up Interval",
"val" : 60,
"pendingState" : null,
"type" : "int",
"data_items" : "Read only",
"value_id" : 72057594136559630,
"units" : "Seconds",
"write_only" : false
},
"2" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Int",
"genre" : "System",
"read_only" : true,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Maximum Wake-up Interval",
"val" : 1800,
"pendingState" : null,
"type" : "int",
"data_items" : "Read only",
"value_id" : 72057594136559650,
"units" : "Seconds",
"write_only" : false
},
"3" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Int",
"genre" : "System",
"read_only" : true,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Default Wake-up Interval",
"val" : 300,
"pendingState" : null,
"type" : "int",
"data_items" : "Read only",
"value_id" : 72057594136559660,
"units" : "Seconds",
"write_only" : false
},
"4" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "Int",
"genre" : "System",
"read_only" : true,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Wake-up Interval Step",
"val" : 60,
"pendingState" : null,
"type" : "int",
"data_items" : "Read only",
"value_id" : 72057594136559680,
"units" : "Seconds",
"write_only" : false
},
"updateTime" : 1
},
"name" : "COMMAND_CLASS_WAKE_UP"
},
"134" : {
"data" : {
"0" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "String",
"genre" : "System",
"read_only" : true,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Library Version",
"val" : "6",
"pendingState" : null,
"type" : "String",
"data_items" : "Read only",
"value_id" : 72057594136592380,
"units" : "",
"write_only" : false
},
"1" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "String",
"genre" : "System",
"read_only" : true,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Protocol Version",
"val" : "3.67",
"pendingState" : null,
"type" : "String",
"data_items" : "Read only",
"value_id" : 72057594136592400,
"units" : "",
"write_only" : false
},
"2" : {
"updateTime" : 1,
"help" : "",
"typeZW" : "String",
"genre" : "System",
"read_only" : true,
"expected_data" : null,
"poll_intensity" : 0,
"name" : "Application Version",
"val" : "1.00",
"pendingState" : null,
"type" : "String",
"data_items" : "Read only",
"value_id" : 72057594136592420,
"units" : "",
"write_only" : false
},
"updateTime" : 1
},
"name" : "COMMAND_CLASS_VERSION"
},
"updateTime" : 1614069602,
"data" : {
"updateTime" : 1614069602
}
}
},
"updateTime" : 1614069602
},
"groups" : {
"updateTime" : 1614069602
},
"command_classes" : {
"0" : {
"hex" : "0x00",
"name" : "COMMAND_CLASS_NO_OPERATION"
},
"49" : {
"hex" : "0x31",
"name" : "COMMAND_CLASS_SENSOR_MULTILEVEL"
},
"67" : {
"hex" : "0x43",
"name" : "COMMAND_CLASS_THERMOSTAT_SETPOINT"
},
"70" : {
"hex" : "0x46",
"name" : "COMMAND_CLASS_CLIMATE_CONTROL_SCHEDULE"
},
"114" : {
"hex" : "0x72",
"name" : "COMMAND_CLASS_MANUFACTURER_SPECIFIC"
},
"117" : {
"hex" : "0x75",
"name" : "COMMAND_CLASS_PROTECTION"
},
"128" : {
"hex" : "0x80",
"name" : "COMMAND_CLASS_BATTERY"
},
"129" : {
"hex" : "0x81",
"name" : "COMMAND_CLASS_CLOCK"
},
"132" : {
"hex" : "0x84",
"name" : "COMMAND_CLASS_WAKE_UP"
},
"134" : {
"hex" : "0x86",
"name" : "COMMAND_CLASS_VERSION"
},
"143" : {
"hex" : "0x8f",
"name" : "COMMAND_CLASS_MULTI_CMD"
}
},
"last_notification" : {
"code" : 4,
"help" : "Report when a node goes to sleep",
"description" : "Sleep",
"next_wakeup" : 1614069902,
"receiveTime" : 1614069602
},
"data" : {
"isReady" : {
"updateTime" : 1614069602,
"value" : true
},
"isRouting" : {
"value" : true
},
"isZwavePlus" : {
"value" : false
},
"basicType" : {
"value" : 4
},
"isListening" : {
"value" : false
},
"is_enable" : {
"value" : true
},
"is_manufacturer_specific_ok" : {
"enabled" : true,
"value" : true
},
"genericType" : {
"value" : 8
},
"isAwake" : {
"updateTime" : 1614069602,
"value" : false
},
"manufacturerProductId" : {
"hex" : "0x0175",
"value" : 373
},
"statistics" : {
"delivered" : 100,
"total" : 3127,
"deliveryTime" : 30
},
"isEnable" : {
"value" : true
},
"specificType" : {
"value" : 4
},
"neighbours" : {
"value" : [
1
]
},
"maxBaudRate" : {
"value" : 40000
},
"isSecurity" : {
"value" : false
},
"state" : {
"value" : "Complete"
},
"version" : {
"value" : 4
},
"location" : {
"value" : "Chambre 01"
},
"manufacturerId" : {
"hex" : "0x0002",
"value" : 2
},
"type" : {
"value" : "Setpoint Thermostat"
},
"product_name" : {
"value" : "Devolo Home Control Radiator Thermostat"
},
"pending_changes" : {
"count" : 0
},
"battery_level" : {
"value" : 84
},
"description" : {
"product_name" : "Devolo Home Control Radiator Thermostat",
"name" : "Thermostat Chambre 1",
"location" : "Chambre 01"
},
"isVirtual" : {
"value" : ""
},
"isFrequentListening" : {
"value" : false
},
"wakeup_interval" : {
"next_wakeup" : 1614069902,
"value" : 300
},
"is_neighbours_ok" : {
"neighbors" : 1,
"enabled" : false,
"value" : true
},
"can_wake_up" : {
"value" : true
},
"lastReceived" : {
"updateTime" : 1614069602
},
"isBeaming" : {
"value" : true
},
"name" : {
"value" : "Thermostat Chambre 1"
},
"manufacturerProductType" : {
"hex" : "0x0005",
"value" : 5
},
"is_groups_ok" : {
"enabled" : false,
"value" : false
},
"isSecured" : {
"enabled" : false,
"value" : false
},
"vendorString" : {
"value" : "Danfoss"
},
"isInfoReceived" : {
"value" : true
},
"isFailed" : {
"value" : false
},
"security" : {
"value" : 0
}
},
"multi_instance" : {
"instances" : 1,
"support" : false
}
}
}`

J'utilise sur le dashboard jeedom simplement le widget sliderbutton de Salvialf qui est mis sur la commande curseur.

Voici aussi le json getinstall

[getinstall.json (2).txt](https://github.com/JeeMateTeam/JeeMate-Project/files/6027700/getinstall.json.2.txt)

**Comment by scalz** [comment]
super merci pour toutes ces infos. fin de journée je vais répliquer ta config et je te tiens au courant :)

**Comment by sagitaz** [comment]
Salut scalz,

Tu as réussi à tester ?

**Comment by sagitaz** [comment]
Avec la dernière version, il y a du mieux sur la gestion des tête thermostatiques.

La configuration des génériques qui fonctionne
**Zigbee danfoss ally** 
![CaptureTzigbeeGenerique](https://user-images.githubusercontent.com/22213453/109677764-42b02a00-7b7a-11eb-90e1-2a18d12fb0a7.PNG)


**Zwave devolo home control**
![CaptureTzwave](https://user-images.githubusercontent.com/22213453/109677795-4ba0fb80-7b7a-11eb-99e9-53e4ba937162.PNG)
et une modification sur la configuration du module ou commande est associé a consigne pending au lieu de consigne sinon cela ne fonctionne pas.
![Tzwave](https://user-images.githubusercontent.com/22213453/109677980-7a1ed680-7b7a-11eb-87a9-802ca5f107a2.PNG)

Il reste comme petit soucis le thermostat qui reviens sur la température. c'est pris en compte sur jeedom mais pas sur l'appli.

**Comment by sagitaz** [comment]
![20210302_174718.gif](https://user-images.githubusercontent.com/22213453/109683449-a557f480-7b7f-11eb-8c28-4b11b617c4ef.gif)

**Comment by scalz** [comment]
ok je regarde ça cette semaine :)

**Comment by sagitaz** [comment]
Plus de soucis sur ce module une fois correctement configuré et avec la dernière version qui gère les DNS jeedom.
