### ISSUE TITLE
Restreindre à la visualisation.

### ISSUE THREAD

**Issue by sagitaz** [JeeMateTeam/JeeMate-Project#82]
Salut,

J'envisage d'installer Jeemate sur une tablette murale chez moi, mais je ne suis pas le seul utilisateur de la maison, la mettant régulièrement en location AirBnB.

Je souhaitais donc savoir si un jour il serais envisageable d'avoir une option (mode visualisation/mode admin), cela afin d'eviter que d'autres personne fasse des modification.

merci

**Comment by scalz** [comment]
oui c'est possible que je l'implémente à l'avenir.
C'est différent ce que tu demandes, mais sinon l'app tient aussi compte des droits users jeedom si besoin.
je verrai comment ajouter ce que tu veux dans l'existant.

**Comment by sagitaz** [comment]
Merci,

J'ai vu et tester une configuration avec un utilisateur "visiteur" ayant comme droit que consulté, cela permet déjà de bloquer pas mal de chose critique.

C'était une idée mais j'ai pas encore la tablette au mur 😉

**Comment by sagitaz** [comment]
Toujours dans la même optique,  demander le code pour fermer l’application.
