### ISSUE TITLE
[Bug] Page vide/blanche

### ISSUE THREAD

**Issue by sagitaz** [JeeMateTeam/JeeMate-Project#83]
Depuis les vignettes des résumes, sur click.

Portes ==> ko (page vide)
Fenêtres ==> ko (page vide)

Les vignettes des autres résumés mène bien soit a l'historique, soit à la commande, soit à rien si juste on/off.

Pour le retour d'état sur commande on/off, il faut fermer le résumé et le rouvrir pour que le changement d'état soit pris en compte.

Appli au top, je continue mes tests.

**Comment by scalz** [comment]
Merci :)

je viens de test:
- résumés portes et et fenêtres ok
- idem les tuiles se rafraichissent bien

Par rapport aux résumés vides, pour l'instant (c'est temporaire) je base le résumés sur le nom des clés jeedom. Aurais-tu par hasard changé ces clés dans jeedom? (opening et window)

Pour le retour d'etat, afin de savoir si c'est coté plugin ou app, pourrais tu :
- activer  les logs debug jeedom pour le plugin
- restart l'app
- une fois sur la page résumé dans l'app, alors tu effaces le log jeemate_node coté jeedom
- clic sur la tuile. tu devrais voir dans le log node un event qui est envoyé à l'app.
Si pas d'event dans le log, alors c'est coté plugin. c'est afin de savoir.

**Comment by sagitaz** [comment]
**Pour le retour d'état :**
J'ai bien un log lors de l'appuie sur la tuile (ici une prise ikea on/off).

Ma prise est id 395 (état=2320, on=2321, off=2322)
le log :
`{"type":"event","id":"2320","value":"0","JeeMateEquip":["601","607"]}`
si je ne sors pas du résumé prise afin de mettre à jour l'état alors je peux spammer la tuile en click et il n'y as plus de log.

**Pour les portes et fenêtres :**
En effet, j'avais modifié les noms des résumés dans Jeedom mais pas que pour ceux là :
![Capture-resumé-jeedom](https://user-images.githubusercontent.com/22213453/108912199-9970ad80-7628-11eb-94a7-9ef46a6f7d22.PNG)
Même en mettant door et window, suivi d'un regen interface cela ne change pas.

Un petit gif parle mieux que du texte, tu as dessus les 2 petit soucis que je rencontre.
![jeemate](https://user-images.githubusercontent.com/22213453/108913905-ee152800-762a-11eb-8c06-d3f3e97b11b0.gif)

**Comment by scalz** [comment]
ok j'ai vu le coup de ta page blanche. cela se passe en Theme Morphic. Sur le thème Glass, il n'y a pas le souci. sera corrigé dans la prochaine version

**Comment by sagitaz** [comment]
Mise à jour faite.

Page blanche sur thème Morphic = soucis réglé. 👍 
Pour le refresh, le soucis est toujours présent (sur les résumé ou sur les favoris)

**Comment by scalz** [comment]
ok cool.
pour le souci de refresh ça te le fait en 4G ou en wifi? si wifi, alors local ou non ?
ça te le fait uniquement sur les tuiles de résumés ou bien aussi sur les favoris?
pour l'instant je n'arrive pas à reproduire..j'ai beau switcher de 4g à wifi local ou non, ça refresh de mon coté

**Comment by sagitaz** [comment]
Cela me le fait en 4g ou wifi non local, je fais les tests hors de chez moi ayant des locataires en ce moment à la maison.

Je compare l'écran jeemate au dashboard jeedom.

Je le suis aussi demandé si ce n'était pas ça le soucis (4g) car j'ai aussi le soucis de refresh sur les consignes des têtes thermostatiques.

Si tu as besoin de quoique ce soit pour debugger, demande moi.

**Comment by scalz** [comment]
Le souci a normalement été résolu avec la dernière mise à jour de l'app.
donc je clos cette issue.
S'il y a toujours un souci, on réouvrira :)
