### ISSUE TITLE
Problème icone dans notification

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#84]
Salut
J'ai creusé plus et j'ai des cas où j'ai la bonne syntaxe mais pas d'icone affiché 👍 
title=COVID;customIcon=fas fa-hands-wash;groupName=Alarme;iconColor=ff0000

**Comment by scalz** [comment]
oki merci. je vais regénérer mes packs di'cones dès que j'ai un moment. en attendant je viens de l'ajouter. par contre ce sera en camelCase: fa-handsWash

**Comment by sebfar9172** [comment]
c'est quoi camelCase ?

**Comment by scalz** [comment]
elle est rigolote ta notif ^^
camelCase c'est un type de notation en dev, à l'image d'un chameau, on met la 1ere lettre d'un mot en majuscule.
camelCase
handsWash
maVariable
unExempleAvecPlusieursMots

**Comment by sebfar9172** [comment]
C'est pour nous faire penser à nous laver les mains quand on rentre :)

**Comment by scalz** [comment]
oui c'est pas bête
le camelCase, c'est en attendant que je regénère mes packs avec la notation classique web

**Comment by sebfar9172** [comment]
franchement c'est top des animations, le lavelinge est en route et le hublot tourne :)

**Comment by scalz** [comment]
ahah excellent ^^

**Comment by ThibautTrarbach** [comment]
Les notifications vont beaucoup changé, dans la prochaine maj, rouvrir une issue si de nouveaux des problème
