### ISSUE TITLE
Ajout d'icone pour les tuiles prises

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#86]
Salut
Pourrais-tu ajouter des icones pour les tuiles prises du type imprimante, brosse à dent ou autres :)

**Comment by scalz** [comment]
c'est prévu et en cours dans l'issue 85.
mais en attendant que cela soit complètement dispo, si c'est vraiment des icones que tu souhaites, tu peux m'envoyer en MP sur discord celles que tu as vu et je les ajouterai pour la prochaine version

**Comment by ThibautTrarbach** [comment]
#85
