### ISSUE TITLE
Tuiles résumés.

### ISSUE THREAD

**Issue by sagitaz** [JeeMateTeam/JeeMate-Project#87]
Lorsqu'on est sur l'affichage des tuiles d'un résumé, la réorganisation n'est pas pris en compte. On peut glisser une tuile à un autre emplacement mais il n'y reste pas.

Pour les résumés personnalisés, il n'est pas affiché les équipements associés.

Par exemple j'ai un résumé thermostats auquel j'ai associé toutes les consignes des têtes thermostatique de la maison, cela me permet d'accéder rapidement au réglage de chaques tête.

Exemple depuis la synthèse de Jeedom.
![IMG_20210225_232145.jpg](https://user-images.githubusercontent.com/22213453/109227255-50536180-77c0-11eb-9448-8d1e16488b03.jpg)

![Screenshot_2021-02-25-23-21-54-625_com.android.chrome.jpg](https://user-images.githubusercontent.com/22213453/109227271-56494280-77c0-11eb-89db-78a2e0df5294.jpg)

**Comment by scalz** [comment]
Salut,
effectivement pour l'instant, je n'affiche les tuiles que pour les clés de base de jeedom. Je n'ai pas encore fait pour les clés customisées par les users, il faut que je vois avec Thibaut pour cela.

Concernant la réorganisation, en effet, pour l'instant je ne l'ai pas mises sur les résumés. mais c'est prévu.
Pour l'instant la réorganisation est dispo pour:
- onglet Favoris
- onglet Pièces
- les groupes

Je vois ça asap :)

**Comment by sagitaz** [comment]
Au top, merci.
