### ISSUE TITLE
Scan QR code via galerie

### ISSUE THREAD

**Issue by pyreneum** [JeeMateTeam/JeeMate-Project#89]
J'ai DL le QR code et au moment du scan je découvre la possibilité d'ouvrir la galerie.. hiha!＼(°o°)／
Mais apres sélection du QR code je reviens sur le menu config et le QR code n'est pas appliqué
Ca attendra demain de redémarrer le PC pour scan habituel

Juste au cas ou
Merci pour le dev, hâte!

**Comment by scalz** [comment]
En fait c'est normal, car je ne l'ai pas encore implémenté ^^
pour l'instant il faut passer par l'appareil photo
je fais ça asap

**Comment by scalz** [comment]
Il y  a un souci avec la lib pour le faire depuis la fenetre du scan.
C'est pourquoi, dans les dernières versions de l'app, j'ai ajouté l'option pour pouvoir scanner un qrcode depuis un fichier image.
La fonction est donc disponible. Je clos cette issue du coup
