### ISSUE TITLE
Changement de nom d'alarme non prise en compte dans les favoris

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#90]
Bonjour
J'ai changé le nom des alarmes. J'ai renvoyer les équipements par le plugin et regénérer dans la configuration de l'application, le nom des alarmes a bien changé dans le menu alarmes mais quand j'ajoute des équipements par les favoris c'est toujours les anciens noms

**Comment by sebfar9172** [comment]
Si je réinitialise l'application en vidant les données et le cache cela fonctionne

**Comment by scalz** [comment]
ok merci pour l'info. je regarde ça dans la semaine
