### ISSUE TITLE
Plugin Météo.

### ISSUE THREAD

**Issue by sagitaz** [JeeMateTeam/JeeMate-Project#92]
J'utilise le plugin Weather pour la météo, sur Jeemate aucun soucis la météo est bien affiché, juste peut être adapter la largeur du cadre ou ce trouve le nom pour s'adapter au texte + changer le contraste en fonction de l'image, sur l'exemple c'est peu lisible.

![Screenshot_2021-03-01-11-37-10-686_com scalz JeeMate](https://user-images.githubusercontent.com/22213453/109486702-8411de00-7a83-11eb-9af7-9e1eed99aafc.jpg)

Sinon, c''est vraiment top ces widgets.

**Comment by sagitaz** [comment]
Je verrai demain avec le beau temps mais déjà le titre c'est nickel, c'est top.
![Uploading Screenshot_2021-03-27-21-53-02-879_com.scalz.JeeMate.jpg…]()

**Comment by scalz** [comment]
je clos normalement c'est résolu
