### ISSUE TITLE
L'application ne se lance pas

### ISSUE THREAD

**Issue by Cityloue15** [JeeMateTeam/JeeMate-Project#95]
Bonjour j'ai la version 0.8.9 d'installer sur mon téléphone android et l'application reste bloquée sur la première page.
![app](https://user-images.githubusercontent.com/73710807/109634773-ec2af780-7b49-11eb-8ba3-0a35eb8b324d.jpg)

**Comment by sagitaz** [comment]
Va dans les paramètres de l'application et efface le cache et les donnée.

Ensuite tu démarre l'application et tu reconfigure ton jeedom + regénère l'interface.

Enjoy 👍

**Comment by Cityloue15** [comment]
Parfait, merci =)
