### ISSUE TITLE
L'état du mode pour le thermostat ne se rafraichit pas

### ISSUE THREAD

**Issue by sebfar9172** [JeeMateTeam/JeeMate-Project#96]
Bonjour
Si je change le mode du thermostat cela est bien pris en compte mais visuellement dans l'application il est toujours sur l'ancien mode. Si je change de thermostat et que je reviens dessus, le mode est bon.

**Comment by scalz** [comment]
Salut,
as-tu toujours le souci avec la dernière version?

**Comment by sebfar9172** [comment]
Salut c'est bon on peut clore
